-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ReadHit is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    i_addr_V : IN STD_LOGIC_VECTOR (31 downto 0);
    valid_V : IN STD_LOGIC_VECTOR (3 downto 0);
    tag_0_V_read : IN STD_LOGIC_VECTOR (27 downto 0);
    tag_1_V_read : IN STD_LOGIC_VECTOR (27 downto 0);
    tag_2_V_read : IN STD_LOGIC_VECTOR (27 downto 0);
    tag_3_V_read : IN STD_LOGIC_VECTOR (27 downto 0);
    dataArray_0_V_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    dataArray_0_V_ce0 : OUT STD_LOGIC;
    dataArray_0_V_q0 : IN STD_LOGIC_VECTOR (511 downto 0);
    dataArray_1_V_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    dataArray_1_V_ce0 : OUT STD_LOGIC;
    dataArray_1_V_q0 : IN STD_LOGIC_VECTOR (511 downto 0);
    dataArray_2_V_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    dataArray_2_V_ce0 : OUT STD_LOGIC;
    dataArray_2_V_q0 : IN STD_LOGIC_VECTOR (511 downto 0);
    dataArray_3_V_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    dataArray_3_V_ce0 : OUT STD_LOGIC;
    dataArray_3_V_q0 : IN STD_LOGIC_VECTOR (511 downto 0);
    mruArray_V_6_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    mruArray_V_6_ce0 : OUT STD_LOGIC;
    mruArray_V_6_we0 : OUT STD_LOGIC;
    mruArray_V_6_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    mruArray_V_6_q0 : IN STD_LOGIC_VECTOR (3 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (511 downto 0) );
end;


architecture behav of ReadHit is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv512_lc_1 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal indexReg_V_fu_173_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal indexReg_V_reg_396 : STD_LOGIC_VECTOR (3 downto 0);
    signal mruArray_V_5_addr_reg_404 : STD_LOGIC_VECTOR (3 downto 0);
    signal newSel2_fu_336_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal newSel2_reg_409 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_193_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_s_fu_357_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tagReg_V_fu_183_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_38_fu_202_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_206_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_39_fu_218_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_31_1_fu_226_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_41_fu_252_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_31_3_fu_260_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_31_fu_212_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond4_fu_232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp1_fu_272_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_demorgan_fu_284_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_31_2_fu_246_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_fu_290_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp9_fu_296_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_40_fu_238_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_fu_302_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_278_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond6_fu_266_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel1_fu_322_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_fu_316_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel_fu_308_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal newSel10_cast_fu_328_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_35_3_fu_378_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_35_2_fu_373_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_35_1_fu_368_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_363_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_V_fu_344_p6 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_return_preg : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);

    component PLRUCache_mux_42_bkb IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (511 downto 0);
        din1 : IN STD_LOGIC_VECTOR (511 downto 0);
        din2 : IN STD_LOGIC_VECTOR (511 downto 0);
        din3 : IN STD_LOGIC_VECTOR (511 downto 0);
        din4 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (511 downto 0) );
    end component;



begin
    PLRUCache_mux_42_bkb_U1 : component PLRUCache_mux_42_bkb
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 512,
        din1_WIDTH => 512,
        din2_WIDTH => 512,
        din3_WIDTH => 512,
        din4_WIDTH => 2,
        dout_WIDTH => 512)
    port map (
        din0 => dataArray_0_V_q0,
        din1 => dataArray_1_V_q0,
        din2 => dataArray_2_V_q0,
        din3 => dataArray_3_V_q0,
        din4 => newSel2_reg_409,
        dout => res_V_fu_344_p6);





    ap_CS_fsm_assign_proc : process(ap_rst, ap_clk)
    begin
        if (ap_rst = '1') then
            ap_CS_fsm <= ap_ST_fsm_state1;
        elsif (ap_clk'event and ap_clk =  '1') then
            ap_CS_fsm <= ap_NS_fsm;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_rst, ap_clk)
    begin
        if (ap_rst = '1') then
            ap_return_preg <= ap_const_lv512_lc_1;
        elsif (ap_clk'event and ap_clk =  '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                ap_return_preg <= res_V_fu_344_p6;
            end if; 
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                indexReg_V_reg_396 <= indexReg_V_fu_173_p4;
                mruArray_V_5_addr_reg_404 <= tmp_fu_193_p1(4 - 1 downto 0);
                newSel2_reg_409 <= newSel2_fu_336_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(ap_CS_fsm_state2, res_V_fu_344_p6, ap_return_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ap_return <= res_V_fu_344_p6;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;

    dataArray_0_V_address0 <= tmp_fu_193_p1(4 - 1 downto 0);

    dataArray_0_V_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dataArray_0_V_ce0 <= ap_const_logic_1;
        else 
            dataArray_0_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    dataArray_1_V_address0 <= tmp_fu_193_p1(4 - 1 downto 0);

    dataArray_1_V_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dataArray_1_V_ce0 <= ap_const_logic_1;
        else 
            dataArray_1_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    dataArray_2_V_address0 <= tmp_fu_193_p1(4 - 1 downto 0);

    dataArray_2_V_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dataArray_2_V_ce0 <= ap_const_logic_1;
        else 
            dataArray_2_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    dataArray_3_V_address0 <= tmp_fu_193_p1(4 - 1 downto 0);

    dataArray_3_V_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            dataArray_3_V_ce0 <= ap_const_logic_1;
        else 
            dataArray_3_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    
    indexReg_V_fu_173_p4_proc : process(i_addr_V)
    variable vlo_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable indexReg_V_fu_173_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_3(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_0(5 - 1 downto 0);
        v0_cpy := i_addr_V;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_0(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_3(5-1 downto 0)));
            for indexReg_V_fu_173_p4_i in 0 to 32-1 loop
                v0_cpy(indexReg_V_fu_173_p4_i) := i_addr_V(32-1-indexReg_V_fu_173_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(32-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        indexReg_V_fu_173_p4 <= resvalue(4-1 downto 0);
    end process;


    mruArray_V_6_address0_assign_proc : process(ap_CS_fsm_state1, mruArray_V_5_addr_reg_404, tmp_fu_193_p1, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mruArray_V_6_address0 <= mruArray_V_5_addr_reg_404;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            mruArray_V_6_address0 <= tmp_fu_193_p1(4 - 1 downto 0);
        else 
            mruArray_V_6_address0 <= "XXXX";
        end if; 
    end process;


    mruArray_V_6_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            mruArray_V_6_ce0 <= ap_const_logic_1;
        else 
            mruArray_V_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    mruArray_V_6_d0 <= (((tmp_35_3_fu_378_p2 & tmp_35_2_fu_373_p2) & tmp_35_1_fu_368_p2) & tmp_8_fu_363_p2);

    mruArray_V_6_we0_assign_proc : process(ap_CS_fsm_state2, tmp_s_fu_357_p2)
    begin
        if (((tmp_s_fu_357_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            mruArray_V_6_we0 <= ap_const_logic_1;
        else 
            mruArray_V_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    newSel10_cast_fu_328_p3 <= 
        ap_const_lv2_3 when (newSel1_fu_322_p2(0) = '1') else 
        ap_const_lv2_0;
    newSel1_fu_322_p2 <= (sel_tmp1_fu_272_p2 and or_cond6_fu_266_p2);
    newSel2_fu_336_p3 <= 
        newSel_fu_308_p3 when (or_cond_fu_316_p2(0) = '1') else 
        newSel10_cast_fu_328_p3;
    newSel_fu_308_p3 <= 
        ap_const_lv2_2 when (sel_tmp7_fu_302_p2(0) = '1') else 
        ap_const_lv2_1;
    or_cond4_fu_232_p2 <= (tmp_39_fu_218_p3 and tmp_31_1_fu_226_p2);
    or_cond6_fu_266_p2 <= (tmp_41_fu_252_p3 and tmp_31_3_fu_260_p2);
    or_cond_31_fu_212_p2 <= (tmp_7_fu_206_p2 and tmp_38_fu_202_p1);
    or_cond_fu_316_p2 <= (sel_tmp7_fu_302_p2 or sel_tmp2_fu_278_p2);
    sel_tmp1_fu_272_p2 <= (or_cond_31_fu_212_p2 xor ap_const_lv1_1);
    sel_tmp2_fu_278_p2 <= (sel_tmp1_fu_272_p2 and or_cond4_fu_232_p2);
    sel_tmp6_demorgan_fu_284_p2 <= (or_cond_31_fu_212_p2 or or_cond4_fu_232_p2);
    sel_tmp6_fu_290_p2 <= (sel_tmp6_demorgan_fu_284_p2 xor ap_const_lv1_1);
    sel_tmp7_fu_302_p2 <= (tmp_40_fu_238_p3 and tmp9_fu_296_p2);
    
    tagReg_V_fu_183_p4_proc : process(i_addr_V)
    variable vlo_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tagReg_V_fu_183_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_1F(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_4(5 - 1 downto 0);
        v0_cpy := i_addr_V;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_4(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_1F(5-1 downto 0)));
            for tagReg_V_fu_183_p4_i in 0 to 32-1 loop
                v0_cpy(tagReg_V_fu_183_p4_i) := i_addr_V(32-1-tagReg_V_fu_183_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(32-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tagReg_V_fu_183_p4 <= resvalue(28-1 downto 0);
    end process;

    tmp9_fu_296_p2 <= (tmp_31_2_fu_246_p2 and sel_tmp6_fu_290_p2);
    tmp_31_1_fu_226_p2 <= "1" when (tagReg_V_fu_183_p4 = tag_1_V_read) else "0";
    tmp_31_2_fu_246_p2 <= "1" when (tagReg_V_fu_183_p4 = tag_2_V_read) else "0";
    tmp_31_3_fu_260_p2 <= "1" when (tagReg_V_fu_183_p4 = tag_3_V_read) else "0";
    tmp_35_1_fu_368_p2 <= "1" when (indexReg_V_reg_396 = ap_const_lv4_1) else "0";
    tmp_35_2_fu_373_p2 <= "1" when (indexReg_V_reg_396 = ap_const_lv4_2) else "0";
    tmp_35_3_fu_378_p2 <= "1" when (indexReg_V_reg_396 = ap_const_lv4_3) else "0";
    tmp_38_fu_202_p1 <= valid_V(1 - 1 downto 0);
    tmp_39_fu_218_p3 <= valid_V(1 downto 1);
    tmp_40_fu_238_p3 <= valid_V(2 downto 2);
    tmp_41_fu_252_p3 <= valid_V(3 downto 3);
    tmp_7_fu_206_p2 <= "1" when (tagReg_V_fu_183_p4 = tag_0_V_read) else "0";
    tmp_8_fu_363_p2 <= "1" when (indexReg_V_reg_396 = ap_const_lv4_0) else "0";
    tmp_fu_193_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(indexReg_V_fu_173_p4),64));
    tmp_s_fu_357_p2 <= "1" when (mruArray_V_6_q0 = ap_const_lv4_F) else "0";
end behav;
