-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ReadMiss is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    i_addr_V : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_dram_V_AWVALID : OUT STD_LOGIC;
    m_axi_dram_V_AWREADY : IN STD_LOGIC;
    m_axi_dram_V_AWADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_dram_V_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dram_V_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_dram_V_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_dram_V_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_dram_V_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_dram_V_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_dram_V_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_dram_V_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_dram_V_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_dram_V_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dram_V_WVALID : OUT STD_LOGIC;
    m_axi_dram_V_WREADY : IN STD_LOGIC;
    m_axi_dram_V_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    m_axi_dram_V_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_dram_V_WLAST : OUT STD_LOGIC;
    m_axi_dram_V_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dram_V_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dram_V_ARVALID : OUT STD_LOGIC;
    m_axi_dram_V_ARREADY : IN STD_LOGIC;
    m_axi_dram_V_ARADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_dram_V_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dram_V_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_dram_V_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_dram_V_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_dram_V_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_dram_V_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_dram_V_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_dram_V_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_dram_V_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_dram_V_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dram_V_RVALID : IN STD_LOGIC;
    m_axi_dram_V_RREADY : OUT STD_LOGIC;
    m_axi_dram_V_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    m_axi_dram_V_RLAST : IN STD_LOGIC;
    m_axi_dram_V_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dram_V_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dram_V_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_dram_V_BVALID : IN STD_LOGIC;
    m_axi_dram_V_BREADY : OUT STD_LOGIC;
    m_axi_dram_V_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_dram_V_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_dram_V_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    dram_V_offset : IN STD_LOGIC_VECTOR (25 downto 0);
    valid_V : IN STD_LOGIC_VECTOR (3 downto 0);
    tag_0_V_read : IN STD_LOGIC_VECTOR (27 downto 0);
    tag_1_V_read : IN STD_LOGIC_VECTOR (27 downto 0);
    tag_2_V_read : IN STD_LOGIC_VECTOR (27 downto 0);
    tag_3_V_read : IN STD_LOGIC_VECTOR (27 downto 0);
    validArray_V_4_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    validArray_V_4_ce0 : OUT STD_LOGIC;
    validArray_V_4_we0 : OUT STD_LOGIC;
    validArray_V_4_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    tagArray_0_V_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    tagArray_0_V_ce0 : OUT STD_LOGIC;
    tagArray_0_V_we0 : OUT STD_LOGIC;
    tagArray_0_V_d0 : OUT STD_LOGIC_VECTOR (27 downto 0);
    tagArray_1_V_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    tagArray_1_V_ce0 : OUT STD_LOGIC;
    tagArray_1_V_we0 : OUT STD_LOGIC;
    tagArray_1_V_d0 : OUT STD_LOGIC_VECTOR (27 downto 0);
    tagArray_2_V_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    tagArray_2_V_ce0 : OUT STD_LOGIC;
    tagArray_2_V_we0 : OUT STD_LOGIC;
    tagArray_2_V_d0 : OUT STD_LOGIC_VECTOR (27 downto 0);
    tagArray_3_V_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    tagArray_3_V_ce0 : OUT STD_LOGIC;
    tagArray_3_V_we0 : OUT STD_LOGIC;
    tagArray_3_V_d0 : OUT STD_LOGIC_VECTOR (27 downto 0);
    dataArray_0_V_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    dataArray_0_V_ce0 : OUT STD_LOGIC;
    dataArray_0_V_we0 : OUT STD_LOGIC;
    dataArray_0_V_d0 : OUT STD_LOGIC_VECTOR (511 downto 0);
    dataArray_0_V_q0 : IN STD_LOGIC_VECTOR (511 downto 0);
    dataArray_1_V_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    dataArray_1_V_ce0 : OUT STD_LOGIC;
    dataArray_1_V_we0 : OUT STD_LOGIC;
    dataArray_1_V_d0 : OUT STD_LOGIC_VECTOR (511 downto 0);
    dataArray_1_V_q0 : IN STD_LOGIC_VECTOR (511 downto 0);
    dataArray_2_V_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    dataArray_2_V_ce0 : OUT STD_LOGIC;
    dataArray_2_V_we0 : OUT STD_LOGIC;
    dataArray_2_V_d0 : OUT STD_LOGIC_VECTOR (511 downto 0);
    dataArray_2_V_q0 : IN STD_LOGIC_VECTOR (511 downto 0);
    dataArray_3_V_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    dataArray_3_V_ce0 : OUT STD_LOGIC;
    dataArray_3_V_we0 : OUT STD_LOGIC;
    dataArray_3_V_d0 : OUT STD_LOGIC_VECTOR (511 downto 0);
    dataArray_3_V_q0 : IN STD_LOGIC_VECTOR (511 downto 0);
    mruArray_V_4_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    mruArray_V_4_ce0 : OUT STD_LOGIC;
    mruArray_V_4_we0 : OUT STD_LOGIC;
    mruArray_V_4_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    mruArray_V_4_q0 : IN STD_LOGIC_VECTOR (3 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (511 downto 0) );
end;


architecture behav of ReadMiss is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (15 downto 0) := "0000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (15 downto 0) := "0000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (15 downto 0) := "0000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (15 downto 0) := "0000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (15 downto 0) := "0001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (15 downto 0) := "0010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (15 downto 0) := "0100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv64_FFFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (63 downto 0) := "1111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal dram_V_blk_n_AR : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal dram_V_blk_n_R : STD_LOGIC;
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal dram_V_blk_n_AW : STD_LOGIC;
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal dram_V_blk_n_W : STD_LOGIC;
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal dram_V_blk_n_B : STD_LOGIC;
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal isEvict_2_reg_933 : STD_LOGIC_VECTOR (0 downto 0);
    signal indexReg_V_fu_354_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal indexReg_V_reg_860 : STD_LOGIC_VECTOR (3 downto 0);
    signal tagReg_V_fu_364_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tagReg_V_reg_870 : STD_LOGIC_VECTOR (27 downto 0);
    signal sext_cast_fu_378_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_cast_reg_878 : STD_LOGIC_VECTOR (32 downto 0);
    signal sum_fu_382_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal sum_reg_883 : STD_LOGIC_VECTOR (32 downto 0);
    signal ap_sig_ioackin_m_axi_dram_V_ARREADY : STD_LOGIC;
    signal tmp_fu_398_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_reg_894 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal mruArray_V_3_addr_reg_911 : STD_LOGIC_VECTOR (3 downto 0);
    signal tempMru_V_reg_916 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal tempValid_V_2_fu_620_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tempValid_V_2_reg_921 : STD_LOGIC_VECTOR (3 downto 0);
    signal Hi_assign_fu_674_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal Hi_assign_reg_926 : STD_LOGIC_VECTOR (2 downto 0);
    signal isEvict_2_fu_736_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Hi_assign_cast_fu_742_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal Hi_assign_cast_reg_937 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_dramBlockR_V_reg_943 : STD_LOGIC_VECTOR (511 downto 0);
    signal tmp_34_fu_745_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_34_reg_951 : STD_LOGIC_VECTOR (1 downto 0);
    signal sum3_fu_773_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal sum3_reg_976 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp_5_fu_778_p6 : STD_LOGIC_VECTOR (511 downto 0);
    signal tmp_5_reg_981 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_sig_ioackin_m_axi_dram_V_AWREADY : STD_LOGIC;
    signal dataArray_0_V_addr_gep_fu_285_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal dataArray_1_V_addr_gep_fu_292_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal dataArray_2_V_addr_gep_fu_299_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal dataArray_3_V_addr_gep_fu_306_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal sum_cast_fu_388_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sum3_cast_fu_791_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_reg_ioackin_m_axi_dram_V_ARREADY : STD_LOGIC := '0';
    signal ap_reg_ioackin_m_axi_dram_V_AWREADY : STD_LOGIC := '0';
    signal ap_block_state16 : BOOLEAN;
    signal ap_reg_ioackin_m_axi_dram_V_WREADY : STD_LOGIC := '0';
    signal ap_sig_ioackin_m_axi_dram_V_WREADY : STD_LOGIC;
    signal tmp_35_fu_801_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_821_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_cast_fu_374_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp_32_fu_448_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_33_fu_464_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_402_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_26_fu_408_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp_fu_480_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_28_fu_416_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_fu_432_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp1_fu_486_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_492_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_fu_504_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp9_fu_516_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp10_fu_522_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_fu_510_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_528_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp3_fu_498_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_534_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_27_fu_412_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp12_fu_548_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_29_fu_424_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp13_fu_554_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp14_fu_560_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp15_fu_566_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp11_fu_540_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal sel_tmp19_demorgan_fu_580_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp16_fu_572_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal sel_tmp23_fu_594_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp20_fu_586_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_31_fu_440_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp4_fu_608_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp26_fu_614_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp24_fu_600_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_640_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp28_fu_636_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal sel_tmp27_fu_628_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal sel_tmp29_fu_646_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal sel_tmp30_fu_654_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_s_fu_456_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal sel_tmp50_cast_fu_662_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_3_fu_472_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal sel_tmp31_fu_666_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp5_fu_682_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_1_not_fu_694_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp6_fu_700_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_sel_tmp_fu_706_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp7_fu_712_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp32_fu_688_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp33_fu_718_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp34_fu_724_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_sel_tmp2_fu_730_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Repl2_2_fu_748_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Repl2_2_fu_748_p6 : STD_LOGIC_VECTOR (27 downto 0);
    signal p_Result_s_fu_762_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_cast_fu_769_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal p_Result_4_fu_813_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_28_3_fu_842_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_28_2_fu_837_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_28_1_fu_832_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_827_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (15 downto 0);

    component PLRUCache_mux_42_cud IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (27 downto 0);
        din1 : IN STD_LOGIC_VECTOR (27 downto 0);
        din2 : IN STD_LOGIC_VECTOR (27 downto 0);
        din3 : IN STD_LOGIC_VECTOR (27 downto 0);
        din4 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (27 downto 0) );
    end component;


    component PLRUCache_mux_42_bkb IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (511 downto 0);
        din1 : IN STD_LOGIC_VECTOR (511 downto 0);
        din2 : IN STD_LOGIC_VECTOR (511 downto 0);
        din3 : IN STD_LOGIC_VECTOR (511 downto 0);
        din4 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (511 downto 0) );
    end component;



begin
    PLRUCache_mux_42_cud_U26 : component PLRUCache_mux_42_cud
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 28,
        din1_WIDTH => 28,
        din2_WIDTH => 28,
        din3_WIDTH => 28,
        din4_WIDTH => 2,
        dout_WIDTH => 28)
    port map (
        din0 => tag_0_V_read,
        din1 => tag_1_V_read,
        din2 => tag_2_V_read,
        din3 => tag_3_V_read,
        din4 => p_Repl2_2_fu_748_p5,
        dout => p_Repl2_2_fu_748_p6);

    PLRUCache_mux_42_bkb_U27 : component PLRUCache_mux_42_bkb
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 512,
        din1_WIDTH => 512,
        din2_WIDTH => 512,
        din3_WIDTH => 512,
        din4_WIDTH => 2,
        dout_WIDTH => 512)
    port map (
        din0 => dataArray_0_V_q0,
        din1 => dataArray_1_V_q0,
        din2 => dataArray_2_V_q0,
        din3 => dataArray_3_V_q0,
        din4 => tmp_34_reg_951,
        dout => tmp_5_fu_778_p6);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_reg_ioackin_m_axi_dram_V_ARREADY_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ioackin_m_axi_dram_V_ARREADY <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                    if ((ap_sig_ioackin_m_axi_dram_V_ARREADY = ap_const_logic_1)) then 
                        ap_reg_ioackin_m_axi_dram_V_ARREADY <= ap_const_logic_0;
                    elsif ((m_axi_dram_V_ARREADY = ap_const_logic_1)) then 
                        ap_reg_ioackin_m_axi_dram_V_ARREADY <= ap_const_logic_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ioackin_m_axi_dram_V_AWREADY_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ioackin_m_axi_dram_V_AWREADY <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                    if ((ap_sig_ioackin_m_axi_dram_V_AWREADY = ap_const_logic_1)) then 
                        ap_reg_ioackin_m_axi_dram_V_AWREADY <= ap_const_logic_0;
                    elsif ((m_axi_dram_V_AWREADY = ap_const_logic_1)) then 
                        ap_reg_ioackin_m_axi_dram_V_AWREADY <= ap_const_logic_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ioackin_m_axi_dram_V_WREADY_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ioackin_m_axi_dram_V_WREADY <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                    if ((ap_sig_ioackin_m_axi_dram_V_WREADY = ap_const_logic_1)) then 
                        ap_reg_ioackin_m_axi_dram_V_WREADY <= ap_const_logic_0;
                    elsif ((m_axi_dram_V_WREADY = ap_const_logic_1)) then 
                        ap_reg_ioackin_m_axi_dram_V_WREADY <= ap_const_logic_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((m_axi_dram_V_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    Hi_assign_cast_reg_937(2 downto 0) <= Hi_assign_cast_fu_742_p1(2 downto 0);
                i_dramBlockR_V_reg_943 <= m_axi_dram_V_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                Hi_assign_reg_926 <= Hi_assign_fu_674_p3;
                isEvict_2_reg_933 <= isEvict_2_fu_736_p2;
                tempMru_V_reg_916 <= mruArray_V_4_q0;
                tempValid_V_2_reg_921 <= tempValid_V_2_fu_620_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                indexReg_V_reg_860 <= indexReg_V_fu_354_p4;
                    sext_cast_reg_878(25 downto 0) <= sext_cast_fu_378_p1(25 downto 0);
                sum_reg_883 <= sum_fu_382_p2;
                tagReg_V_reg_870 <= tagReg_V_fu_364_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                mruArray_V_3_addr_reg_911 <= tmp_fu_398_p1(4 - 1 downto 0);
                    tmp_reg_894(3 downto 0) <= tmp_fu_398_p1(3 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((m_axi_dram_V_RVALID = ap_const_logic_1) and (isEvict_2_reg_933 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                sum3_reg_976 <= sum3_fu_773_p2;
                tmp_34_reg_951 <= tmp_34_fu_745_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_sig_ioackin_m_axi_dram_V_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                tmp_5_reg_981 <= tmp_5_fu_778_p6;
            end if;
        end if;
    end process;
    sext_cast_reg_878(32 downto 26) <= "0000000";
    tmp_reg_894(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    Hi_assign_cast_reg_937(31 downto 3) <= "00000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, m_axi_dram_V_RVALID, m_axi_dram_V_BVALID, ap_CS_fsm_state2, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state16, isEvict_2_reg_933, ap_sig_ioackin_m_axi_dram_V_ARREADY, ap_sig_ioackin_m_axi_dram_V_AWREADY, ap_sig_ioackin_m_axi_dram_V_WREADY)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_sig_ioackin_m_axi_dram_V_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if (((m_axi_dram_V_RVALID = ap_const_logic_1) and (isEvict_2_reg_933 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state16;
                elsif (((m_axi_dram_V_RVALID = ap_const_logic_1) and (isEvict_2_reg_933 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                if (((ap_sig_ioackin_m_axi_dram_V_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state11 => 
                if (((ap_sig_ioackin_m_axi_dram_V_WREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                if ((not(((m_axi_dram_V_BVALID = ap_const_logic_0) and (isEvict_2_reg_933 = ap_const_lv1_1))) and (ap_const_logic_1 = ap_CS_fsm_state16))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state16;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXX";
        end case;
    end process;
    Hi_assign_cast_fu_742_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Hi_assign_reg_926),32));
    Hi_assign_fu_674_p3 <= 
        p_3_fu_472_p3 when (sel_tmp26_fu_614_p2(0) = '1') else 
        sel_tmp31_fu_666_p3;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_block_state16_assign_proc : process(m_axi_dram_V_BVALID, isEvict_2_reg_933)
    begin
                ap_block_state16 <= ((m_axi_dram_V_BVALID = ap_const_logic_0) and (isEvict_2_reg_933 = ap_const_lv1_1));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, m_axi_dram_V_BVALID, ap_CS_fsm_state16, isEvict_2_reg_933)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or (not(((m_axi_dram_V_BVALID = ap_const_logic_0) and (isEvict_2_reg_933 = ap_const_lv1_1))) and (ap_const_logic_1 = ap_CS_fsm_state16)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(m_axi_dram_V_BVALID, ap_CS_fsm_state16, isEvict_2_reg_933)
    begin
        if ((not(((m_axi_dram_V_BVALID = ap_const_logic_0) and (isEvict_2_reg_933 = ap_const_lv1_1))) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= i_dramBlockR_V_reg_943;

    ap_sig_ioackin_m_axi_dram_V_ARREADY_assign_proc : process(m_axi_dram_V_ARREADY, ap_reg_ioackin_m_axi_dram_V_ARREADY)
    begin
        if ((ap_reg_ioackin_m_axi_dram_V_ARREADY = ap_const_logic_0)) then 
            ap_sig_ioackin_m_axi_dram_V_ARREADY <= m_axi_dram_V_ARREADY;
        else 
            ap_sig_ioackin_m_axi_dram_V_ARREADY <= ap_const_logic_1;
        end if; 
    end process;


    ap_sig_ioackin_m_axi_dram_V_AWREADY_assign_proc : process(m_axi_dram_V_AWREADY, ap_reg_ioackin_m_axi_dram_V_AWREADY)
    begin
        if ((ap_reg_ioackin_m_axi_dram_V_AWREADY = ap_const_logic_0)) then 
            ap_sig_ioackin_m_axi_dram_V_AWREADY <= m_axi_dram_V_AWREADY;
        else 
            ap_sig_ioackin_m_axi_dram_V_AWREADY <= ap_const_logic_1;
        end if; 
    end process;


    ap_sig_ioackin_m_axi_dram_V_WREADY_assign_proc : process(m_axi_dram_V_WREADY, ap_reg_ioackin_m_axi_dram_V_WREADY)
    begin
        if ((ap_reg_ioackin_m_axi_dram_V_WREADY = ap_const_logic_0)) then 
            ap_sig_ioackin_m_axi_dram_V_WREADY <= m_axi_dram_V_WREADY;
        else 
            ap_sig_ioackin_m_axi_dram_V_WREADY <= ap_const_logic_1;
        end if; 
    end process;

    dataArray_0_V_addr_gep_fu_285_p3 <= tmp_reg_894(4 - 1 downto 0);

    dataArray_0_V_address0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state16, tmp_reg_894, dataArray_0_V_addr_gep_fu_285_p3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            dataArray_0_V_address0 <= dataArray_0_V_addr_gep_fu_285_p3;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            dataArray_0_V_address0 <= tmp_reg_894(4 - 1 downto 0);
        else 
            dataArray_0_V_address0 <= "XXXX";
        end if; 
    end process;


    dataArray_0_V_ce0_assign_proc : process(m_axi_dram_V_RVALID, m_axi_dram_V_BVALID, ap_CS_fsm_state9, ap_CS_fsm_state16, isEvict_2_reg_933)
    begin
        if (((not(((m_axi_dram_V_BVALID = ap_const_logic_0) and (isEvict_2_reg_933 = ap_const_lv1_1))) and (ap_const_logic_1 = ap_CS_fsm_state16)) or ((m_axi_dram_V_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9)))) then 
            dataArray_0_V_ce0 <= ap_const_logic_1;
        else 
            dataArray_0_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    dataArray_0_V_d0 <= i_dramBlockR_V_reg_943;

    dataArray_0_V_we0_assign_proc : process(m_axi_dram_V_BVALID, ap_CS_fsm_state16, isEvict_2_reg_933, tmp_35_fu_801_p1)
    begin
        if ((not(((m_axi_dram_V_BVALID = ap_const_logic_0) and (isEvict_2_reg_933 = ap_const_lv1_1))) and (tmp_35_fu_801_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
            dataArray_0_V_we0 <= ap_const_logic_1;
        else 
            dataArray_0_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    dataArray_1_V_addr_gep_fu_292_p3 <= tmp_reg_894(4 - 1 downto 0);

    dataArray_1_V_address0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state16, tmp_reg_894, dataArray_1_V_addr_gep_fu_292_p3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            dataArray_1_V_address0 <= dataArray_1_V_addr_gep_fu_292_p3;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            dataArray_1_V_address0 <= tmp_reg_894(4 - 1 downto 0);
        else 
            dataArray_1_V_address0 <= "XXXX";
        end if; 
    end process;


    dataArray_1_V_ce0_assign_proc : process(m_axi_dram_V_RVALID, m_axi_dram_V_BVALID, ap_CS_fsm_state9, ap_CS_fsm_state16, isEvict_2_reg_933)
    begin
        if (((not(((m_axi_dram_V_BVALID = ap_const_logic_0) and (isEvict_2_reg_933 = ap_const_lv1_1))) and (ap_const_logic_1 = ap_CS_fsm_state16)) or ((m_axi_dram_V_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9)))) then 
            dataArray_1_V_ce0 <= ap_const_logic_1;
        else 
            dataArray_1_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    dataArray_1_V_d0 <= i_dramBlockR_V_reg_943;

    dataArray_1_V_we0_assign_proc : process(m_axi_dram_V_BVALID, ap_CS_fsm_state16, isEvict_2_reg_933, tmp_35_fu_801_p1)
    begin
        if ((not(((m_axi_dram_V_BVALID = ap_const_logic_0) and (isEvict_2_reg_933 = ap_const_lv1_1))) and (tmp_35_fu_801_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
            dataArray_1_V_we0 <= ap_const_logic_1;
        else 
            dataArray_1_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    dataArray_2_V_addr_gep_fu_299_p3 <= tmp_reg_894(4 - 1 downto 0);

    dataArray_2_V_address0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state16, tmp_reg_894, dataArray_2_V_addr_gep_fu_299_p3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            dataArray_2_V_address0 <= dataArray_2_V_addr_gep_fu_299_p3;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            dataArray_2_V_address0 <= tmp_reg_894(4 - 1 downto 0);
        else 
            dataArray_2_V_address0 <= "XXXX";
        end if; 
    end process;


    dataArray_2_V_ce0_assign_proc : process(m_axi_dram_V_RVALID, m_axi_dram_V_BVALID, ap_CS_fsm_state9, ap_CS_fsm_state16, isEvict_2_reg_933)
    begin
        if (((not(((m_axi_dram_V_BVALID = ap_const_logic_0) and (isEvict_2_reg_933 = ap_const_lv1_1))) and (ap_const_logic_1 = ap_CS_fsm_state16)) or ((m_axi_dram_V_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9)))) then 
            dataArray_2_V_ce0 <= ap_const_logic_1;
        else 
            dataArray_2_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    dataArray_2_V_d0 <= i_dramBlockR_V_reg_943;

    dataArray_2_V_we0_assign_proc : process(m_axi_dram_V_BVALID, ap_CS_fsm_state16, isEvict_2_reg_933, tmp_35_fu_801_p1)
    begin
        if ((not(((m_axi_dram_V_BVALID = ap_const_logic_0) and (isEvict_2_reg_933 = ap_const_lv1_1))) and (tmp_35_fu_801_p1 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
            dataArray_2_V_we0 <= ap_const_logic_1;
        else 
            dataArray_2_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    dataArray_3_V_addr_gep_fu_306_p3 <= tmp_reg_894(4 - 1 downto 0);

    dataArray_3_V_address0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state16, tmp_reg_894, dataArray_3_V_addr_gep_fu_306_p3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            dataArray_3_V_address0 <= dataArray_3_V_addr_gep_fu_306_p3;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            dataArray_3_V_address0 <= tmp_reg_894(4 - 1 downto 0);
        else 
            dataArray_3_V_address0 <= "XXXX";
        end if; 
    end process;


    dataArray_3_V_ce0_assign_proc : process(m_axi_dram_V_RVALID, m_axi_dram_V_BVALID, ap_CS_fsm_state9, ap_CS_fsm_state16, isEvict_2_reg_933)
    begin
        if (((not(((m_axi_dram_V_BVALID = ap_const_logic_0) and (isEvict_2_reg_933 = ap_const_lv1_1))) and (ap_const_logic_1 = ap_CS_fsm_state16)) or ((m_axi_dram_V_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9)))) then 
            dataArray_3_V_ce0 <= ap_const_logic_1;
        else 
            dataArray_3_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    dataArray_3_V_d0 <= i_dramBlockR_V_reg_943;

    dataArray_3_V_we0_assign_proc : process(m_axi_dram_V_BVALID, ap_CS_fsm_state16, isEvict_2_reg_933, tmp_35_fu_801_p1)
    begin
        if ((not(((m_axi_dram_V_BVALID = ap_const_logic_0) and (isEvict_2_reg_933 = ap_const_lv1_1))) and (tmp_35_fu_801_p1 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
            dataArray_3_V_we0 <= ap_const_logic_1;
        else 
            dataArray_3_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    dram_V_blk_n_AR_assign_proc : process(m_axi_dram_V_ARREADY, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            dram_V_blk_n_AR <= m_axi_dram_V_ARREADY;
        else 
            dram_V_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    dram_V_blk_n_AW_assign_proc : process(m_axi_dram_V_AWREADY, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            dram_V_blk_n_AW <= m_axi_dram_V_AWREADY;
        else 
            dram_V_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    dram_V_blk_n_B_assign_proc : process(m_axi_dram_V_BVALID, ap_CS_fsm_state16, isEvict_2_reg_933)
    begin
        if (((isEvict_2_reg_933 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
            dram_V_blk_n_B <= m_axi_dram_V_BVALID;
        else 
            dram_V_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    dram_V_blk_n_R_assign_proc : process(m_axi_dram_V_RVALID, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            dram_V_blk_n_R <= m_axi_dram_V_RVALID;
        else 
            dram_V_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    dram_V_blk_n_W_assign_proc : process(m_axi_dram_V_WREADY, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            dram_V_blk_n_W <= m_axi_dram_V_WREADY;
        else 
            dram_V_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    
    indexReg_V_fu_354_p4_proc : process(i_addr_V)
    variable vlo_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable indexReg_V_fu_354_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_3(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_0(5 - 1 downto 0);
        v0_cpy := i_addr_V;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_0(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_3(5-1 downto 0)));
            for indexReg_V_fu_354_p4_i in 0 to 32-1 loop
                v0_cpy(indexReg_V_fu_354_p4_i) := i_addr_V(32-1-indexReg_V_fu_354_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(32-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        indexReg_V_fu_354_p4 <= resvalue(4-1 downto 0);
    end process;

    isEvict_2_fu_736_p2 <= (sel_tmp34_fu_724_p2 and not_sel_tmp2_fu_730_p2);
    m_axi_dram_V_ARADDR <= sum_cast_fu_388_p1(32 - 1 downto 0);
    m_axi_dram_V_ARBURST <= ap_const_lv2_0;
    m_axi_dram_V_ARCACHE <= ap_const_lv4_0;
    m_axi_dram_V_ARID <= ap_const_lv1_0;
    m_axi_dram_V_ARLEN <= ap_const_lv32_1;
    m_axi_dram_V_ARLOCK <= ap_const_lv2_0;
    m_axi_dram_V_ARPROT <= ap_const_lv3_0;
    m_axi_dram_V_ARQOS <= ap_const_lv4_0;
    m_axi_dram_V_ARREGION <= ap_const_lv4_0;
    m_axi_dram_V_ARSIZE <= ap_const_lv3_0;
    m_axi_dram_V_ARUSER <= ap_const_lv1_0;

    m_axi_dram_V_ARVALID_assign_proc : process(ap_CS_fsm_state2, ap_reg_ioackin_m_axi_dram_V_ARREADY)
    begin
        if (((ap_reg_ioackin_m_axi_dram_V_ARREADY = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_dram_V_ARVALID <= ap_const_logic_1;
        else 
            m_axi_dram_V_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_dram_V_AWADDR <= sum3_cast_fu_791_p1(32 - 1 downto 0);
    m_axi_dram_V_AWBURST <= ap_const_lv2_0;
    m_axi_dram_V_AWCACHE <= ap_const_lv4_0;
    m_axi_dram_V_AWID <= ap_const_lv1_0;
    m_axi_dram_V_AWLEN <= ap_const_lv32_1;
    m_axi_dram_V_AWLOCK <= ap_const_lv2_0;
    m_axi_dram_V_AWPROT <= ap_const_lv3_0;
    m_axi_dram_V_AWQOS <= ap_const_lv4_0;
    m_axi_dram_V_AWREGION <= ap_const_lv4_0;
    m_axi_dram_V_AWSIZE <= ap_const_lv3_0;
    m_axi_dram_V_AWUSER <= ap_const_lv1_0;

    m_axi_dram_V_AWVALID_assign_proc : process(ap_CS_fsm_state10, ap_reg_ioackin_m_axi_dram_V_AWREADY)
    begin
        if (((ap_reg_ioackin_m_axi_dram_V_AWREADY = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            m_axi_dram_V_AWVALID <= ap_const_logic_1;
        else 
            m_axi_dram_V_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_dram_V_BREADY_assign_proc : process(m_axi_dram_V_BVALID, ap_CS_fsm_state16, isEvict_2_reg_933)
    begin
        if ((not(((m_axi_dram_V_BVALID = ap_const_logic_0) and (isEvict_2_reg_933 = ap_const_lv1_1))) and (isEvict_2_reg_933 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
            m_axi_dram_V_BREADY <= ap_const_logic_1;
        else 
            m_axi_dram_V_BREADY <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_dram_V_RREADY_assign_proc : process(m_axi_dram_V_RVALID, ap_CS_fsm_state9)
    begin
        if (((m_axi_dram_V_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_dram_V_RREADY <= ap_const_logic_1;
        else 
            m_axi_dram_V_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_dram_V_WDATA <= tmp_5_reg_981;
    m_axi_dram_V_WID <= ap_const_lv1_0;
    m_axi_dram_V_WLAST <= ap_const_logic_0;
    m_axi_dram_V_WSTRB <= ap_const_lv64_FFFFFFFFFFFFFFFF;
    m_axi_dram_V_WUSER <= ap_const_lv1_0;

    m_axi_dram_V_WVALID_assign_proc : process(ap_CS_fsm_state11, ap_reg_ioackin_m_axi_dram_V_WREADY)
    begin
        if (((ap_reg_ioackin_m_axi_dram_V_WREADY = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            m_axi_dram_V_WVALID <= ap_const_logic_1;
        else 
            m_axi_dram_V_WVALID <= ap_const_logic_0;
        end if; 
    end process;


    mruArray_V_4_address0_assign_proc : process(ap_CS_fsm_state16, tmp_fu_398_p1, ap_CS_fsm_state7, mruArray_V_3_addr_reg_911)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            mruArray_V_4_address0 <= mruArray_V_3_addr_reg_911;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            mruArray_V_4_address0 <= tmp_fu_398_p1(4 - 1 downto 0);
        else 
            mruArray_V_4_address0 <= "XXXX";
        end if; 
    end process;


    mruArray_V_4_ce0_assign_proc : process(m_axi_dram_V_BVALID, ap_CS_fsm_state16, isEvict_2_reg_933, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or (not(((m_axi_dram_V_BVALID = ap_const_logic_0) and (isEvict_2_reg_933 = ap_const_lv1_1))) and (ap_const_logic_1 = ap_CS_fsm_state16)))) then 
            mruArray_V_4_ce0 <= ap_const_logic_1;
        else 
            mruArray_V_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    mruArray_V_4_d0 <= (((tmp_28_3_fu_842_p2 & tmp_28_2_fu_837_p2) & tmp_28_1_fu_832_p2) & tmp_6_fu_827_p2);

    mruArray_V_4_we0_assign_proc : process(m_axi_dram_V_BVALID, ap_CS_fsm_state16, isEvict_2_reg_933, tmp_35_fu_801_p1, tmp_3_fu_821_p2)
    begin
        if ((not(((m_axi_dram_V_BVALID = ap_const_logic_0) and (isEvict_2_reg_933 = ap_const_lv1_1))) and (ap_const_logic_1 = ap_CS_fsm_state16) and (((tmp_35_fu_801_p1 = ap_const_lv2_3) and (tmp_3_fu_821_p2 = ap_const_lv1_1)) or ((tmp_35_fu_801_p1 = ap_const_lv2_2) and (tmp_3_fu_821_p2 = ap_const_lv1_1)) or ((tmp_35_fu_801_p1 = ap_const_lv2_1) and (tmp_3_fu_821_p2 = ap_const_lv1_1)) or ((tmp_35_fu_801_p1 = ap_const_lv2_0) and (tmp_3_fu_821_p2 = ap_const_lv1_1))))) then 
            mruArray_V_4_we0 <= ap_const_logic_1;
        else 
            mruArray_V_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    not_sel_tmp2_fu_730_p2 <= (sel_tmp26_fu_614_p2 xor ap_const_lv1_1);
    not_sel_tmp_fu_706_p2 <= (tmp_s_fu_402_p2 or tmp6_fu_700_p2);
    p_3_fu_472_p3 <= 
        ap_const_lv3_4 when (tmp_33_fu_464_p3(0) = '1') else 
        ap_const_lv3_3;
    p_Repl2_2_fu_748_p5 <= Hi_assign_reg_926(2 - 1 downto 0);
    p_Result_1_not_fu_694_p2 <= (tmp_27_fu_412_p1 xor ap_const_lv1_1);
    
    p_Result_4_fu_813_p4_proc : process(tempMru_V_reg_916, Hi_assign_cast_reg_937)
    variable result: std_logic_vector(0 downto 0);
    begin
        p_Result_4_fu_813_p4 <= tempMru_V_reg_916;
        if to_integer(unsigned(Hi_assign_cast_reg_937)) >= tempMru_V_reg_916'low and to_integer(unsigned(Hi_assign_cast_reg_937)) <= tempMru_V_reg_916'high then
            result(0) := '0';
            for i in ap_const_lv4_1'range loop
                result(0) := result(0) or ap_const_lv4_1(i);
            end loop;
            p_Result_4_fu_813_p4(to_integer(unsigned(Hi_assign_cast_reg_937))) <= result(0);
        end if;
    end process;

    p_Result_s_fu_762_p3 <= (p_Repl2_2_fu_748_p6 & indexReg_V_reg_860);
    p_s_fu_456_p3 <= 
        ap_const_lv3_4 when (tmp_32_fu_448_p3(0) = '1') else 
        ap_const_lv3_3;
    sel_tmp10_fu_522_p2 <= (tmp_s_fu_402_p2 and sel_tmp9_fu_516_p2);
    sel_tmp11_fu_540_p3 <= 
        ap_const_lv4_F when (tmp_7_fu_534_p2(0) = '1') else 
        valid_V;
    sel_tmp12_fu_548_p2 <= (tmp_s_fu_402_p2 xor ap_const_lv1_1);
    sel_tmp13_fu_554_p2 <= (tmp_27_fu_412_p1 and sel_tmp12_fu_548_p2);
    sel_tmp14_fu_560_p2 <= (tmp_29_fu_424_p3 xor ap_const_lv1_1);
    sel_tmp15_fu_566_p2 <= (sel_tmp14_fu_560_p2 and sel_tmp13_fu_554_p2);
    sel_tmp16_fu_572_p3 <= 
        valid_V when (sel_tmp15_fu_566_p2(0) = '1') else 
        sel_tmp11_fu_540_p3;
    sel_tmp19_demorgan_fu_580_p2 <= (tmp_s_fu_402_p2 or tmp_27_fu_412_p1);
    sel_tmp1_fu_486_p2 <= (tmp_28_fu_416_p3 and sel_tmp_fu_480_p2);
    sel_tmp20_fu_586_p3 <= 
        sel_tmp16_fu_572_p3 when (sel_tmp19_demorgan_fu_580_p2(0) = '1') else 
        valid_V;
    sel_tmp23_fu_594_p2 <= (tmp_30_fu_432_p3 and sel_tmp1_fu_486_p2);
    sel_tmp24_fu_600_p3 <= 
        ap_const_lv4_F when (sel_tmp23_fu_594_p2(0) = '1') else 
        sel_tmp20_fu_586_p3;
    sel_tmp26_fu_614_p2 <= (tmp4_fu_608_p2 and sel_tmp13_fu_554_p2);
    sel_tmp27_fu_628_p3 <= 
        ap_const_lv2_1 when (sel_tmp7_fu_510_p2(0) = '1') else 
        ap_const_lv2_2;
    sel_tmp28_fu_636_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sel_tmp15_fu_566_p2),2));
    sel_tmp29_fu_646_p3 <= 
        sel_tmp28_fu_636_p1 when (tmp_4_fu_640_p2(0) = '1') else 
        sel_tmp27_fu_628_p3;
    sel_tmp2_fu_492_p2 <= (tmp_30_fu_432_p3 xor ap_const_lv1_1);
    sel_tmp30_fu_654_p3 <= 
        sel_tmp29_fu_646_p3 when (sel_tmp19_demorgan_fu_580_p2(0) = '1') else 
        ap_const_lv2_0;
    sel_tmp31_fu_666_p3 <= 
        p_s_fu_456_p3 when (sel_tmp23_fu_594_p2(0) = '1') else 
        sel_tmp50_cast_fu_662_p1;
    sel_tmp32_fu_688_p2 <= (tmp5_fu_682_p2 or sel_tmp7_fu_510_p2);
    sel_tmp33_fu_718_p2 <= (tmp7_fu_712_p2 and sel_tmp32_fu_688_p2);
    sel_tmp34_fu_724_p2 <= (sel_tmp33_fu_718_p2 or sel_tmp23_fu_594_p2);
    sel_tmp3_fu_498_p2 <= (sel_tmp2_fu_492_p2 and sel_tmp1_fu_486_p2);
    sel_tmp50_cast_fu_662_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sel_tmp30_fu_654_p3),3));
    sel_tmp6_fu_504_p2 <= (tmp_28_fu_416_p3 xor ap_const_lv1_1);
    sel_tmp7_fu_510_p2 <= (sel_tmp_fu_480_p2 and sel_tmp6_fu_504_p2);
    sel_tmp9_fu_516_p2 <= (tmp_26_fu_408_p1 xor ap_const_lv1_1);
    sel_tmp_fu_480_p2 <= (tmp_s_fu_402_p2 and tmp_26_fu_408_p1);
    sext_cast_fu_378_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(dram_V_offset),33));
    sum3_cast_fu_791_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sum3_reg_976),64));
    sum3_fu_773_p2 <= std_logic_vector(unsigned(sext_cast_reg_878) + unsigned(tmp_2_cast_fu_769_p1));
    sum_cast_fu_388_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sum_reg_883),64));
    sum_fu_382_p2 <= std_logic_vector(unsigned(sext_cast_fu_378_p1) + unsigned(tmp_1_cast_fu_374_p1));
    tagArray_0_V_address0 <= tmp_reg_894(4 - 1 downto 0);

    tagArray_0_V_ce0_assign_proc : process(m_axi_dram_V_BVALID, ap_CS_fsm_state16, isEvict_2_reg_933)
    begin
        if ((not(((m_axi_dram_V_BVALID = ap_const_logic_0) and (isEvict_2_reg_933 = ap_const_lv1_1))) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
            tagArray_0_V_ce0 <= ap_const_logic_1;
        else 
            tagArray_0_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    tagArray_0_V_d0 <= tagReg_V_reg_870;

    tagArray_0_V_we0_assign_proc : process(m_axi_dram_V_BVALID, ap_CS_fsm_state16, isEvict_2_reg_933, tmp_35_fu_801_p1)
    begin
        if ((not(((m_axi_dram_V_BVALID = ap_const_logic_0) and (isEvict_2_reg_933 = ap_const_lv1_1))) and (tmp_35_fu_801_p1 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
            tagArray_0_V_we0 <= ap_const_logic_1;
        else 
            tagArray_0_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    tagArray_1_V_address0 <= tmp_reg_894(4 - 1 downto 0);

    tagArray_1_V_ce0_assign_proc : process(m_axi_dram_V_BVALID, ap_CS_fsm_state16, isEvict_2_reg_933)
    begin
        if ((not(((m_axi_dram_V_BVALID = ap_const_logic_0) and (isEvict_2_reg_933 = ap_const_lv1_1))) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
            tagArray_1_V_ce0 <= ap_const_logic_1;
        else 
            tagArray_1_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    tagArray_1_V_d0 <= tagReg_V_reg_870;

    tagArray_1_V_we0_assign_proc : process(m_axi_dram_V_BVALID, ap_CS_fsm_state16, isEvict_2_reg_933, tmp_35_fu_801_p1)
    begin
        if ((not(((m_axi_dram_V_BVALID = ap_const_logic_0) and (isEvict_2_reg_933 = ap_const_lv1_1))) and (tmp_35_fu_801_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
            tagArray_1_V_we0 <= ap_const_logic_1;
        else 
            tagArray_1_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    tagArray_2_V_address0 <= tmp_reg_894(4 - 1 downto 0);

    tagArray_2_V_ce0_assign_proc : process(m_axi_dram_V_BVALID, ap_CS_fsm_state16, isEvict_2_reg_933)
    begin
        if ((not(((m_axi_dram_V_BVALID = ap_const_logic_0) and (isEvict_2_reg_933 = ap_const_lv1_1))) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
            tagArray_2_V_ce0 <= ap_const_logic_1;
        else 
            tagArray_2_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    tagArray_2_V_d0 <= tagReg_V_reg_870;

    tagArray_2_V_we0_assign_proc : process(m_axi_dram_V_BVALID, ap_CS_fsm_state16, isEvict_2_reg_933, tmp_35_fu_801_p1)
    begin
        if ((not(((m_axi_dram_V_BVALID = ap_const_logic_0) and (isEvict_2_reg_933 = ap_const_lv1_1))) and (tmp_35_fu_801_p1 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
            tagArray_2_V_we0 <= ap_const_logic_1;
        else 
            tagArray_2_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    tagArray_3_V_address0 <= tmp_reg_894(4 - 1 downto 0);

    tagArray_3_V_ce0_assign_proc : process(m_axi_dram_V_BVALID, ap_CS_fsm_state16, isEvict_2_reg_933)
    begin
        if ((not(((m_axi_dram_V_BVALID = ap_const_logic_0) and (isEvict_2_reg_933 = ap_const_lv1_1))) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
            tagArray_3_V_ce0 <= ap_const_logic_1;
        else 
            tagArray_3_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    tagArray_3_V_d0 <= tagReg_V_reg_870;

    tagArray_3_V_we0_assign_proc : process(m_axi_dram_V_BVALID, ap_CS_fsm_state16, isEvict_2_reg_933, tmp_35_fu_801_p1)
    begin
        if ((not(((m_axi_dram_V_BVALID = ap_const_logic_0) and (isEvict_2_reg_933 = ap_const_lv1_1))) and (tmp_35_fu_801_p1 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
            tagArray_3_V_we0 <= ap_const_logic_1;
        else 
            tagArray_3_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    
    tagReg_V_fu_364_p4_proc : process(i_addr_V)
    variable vlo_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tagReg_V_fu_364_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_1F(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_4(5 - 1 downto 0);
        v0_cpy := i_addr_V;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_4(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_1F(5-1 downto 0)));
            for tagReg_V_fu_364_p4_i in 0 to 32-1 loop
                v0_cpy(tagReg_V_fu_364_p4_i) := i_addr_V(32-1-tagReg_V_fu_364_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(32-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tagReg_V_fu_364_p4 <= resvalue(28-1 downto 0);
    end process;

    tempValid_V_2_fu_620_p3 <= 
        valid_V when (sel_tmp26_fu_614_p2(0) = '1') else 
        sel_tmp24_fu_600_p3;
    tmp4_fu_608_p2 <= (tmp_31_fu_440_p3 and tmp_29_fu_424_p3);
    tmp5_fu_682_p2 <= (sel_tmp3_fu_498_p2 or sel_tmp10_fu_522_p2);
    tmp6_fu_700_p2 <= (tmp_29_fu_424_p3 or p_Result_1_not_fu_694_p2);
    tmp7_fu_712_p2 <= (sel_tmp19_demorgan_fu_580_p2 and not_sel_tmp_fu_706_p2);
    tmp_1_cast_fu_374_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_addr_V),33));
    tmp_26_fu_408_p1 <= mruArray_V_4_q0(1 - 1 downto 0);
    tmp_27_fu_412_p1 <= valid_V(1 - 1 downto 0);
    tmp_28_1_fu_832_p2 <= "1" when (indexReg_V_reg_860 = ap_const_lv4_1) else "0";
    tmp_28_2_fu_837_p2 <= "1" when (indexReg_V_reg_860 = ap_const_lv4_2) else "0";
    tmp_28_3_fu_842_p2 <= "1" when (indexReg_V_reg_860 = ap_const_lv4_3) else "0";
    tmp_28_fu_416_p3 <= mruArray_V_4_q0(1 downto 1);
    tmp_29_fu_424_p3 <= valid_V(1 downto 1);
    tmp_2_cast_fu_769_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_s_fu_762_p3),33));
    tmp_30_fu_432_p3 <= mruArray_V_4_q0(2 downto 2);
    tmp_31_fu_440_p3 <= valid_V(2 downto 2);
    tmp_32_fu_448_p3 <= mruArray_V_4_q0(3 downto 3);
    tmp_33_fu_464_p3 <= valid_V(3 downto 3);
    tmp_34_fu_745_p1 <= Hi_assign_reg_926(2 - 1 downto 0);
    tmp_35_fu_801_p1 <= Hi_assign_reg_926(2 - 1 downto 0);
    tmp_3_fu_821_p2 <= "1" when (p_Result_4_fu_813_p4 = ap_const_lv4_F) else "0";
    tmp_4_fu_640_p2 <= (sel_tmp15_fu_566_p2 or sel_tmp10_fu_522_p2);
    tmp_6_fu_827_p2 <= "1" when (indexReg_V_reg_860 = ap_const_lv4_0) else "0";
    tmp_7_fu_534_p2 <= (tmp_9_fu_528_p2 or sel_tmp3_fu_498_p2);
    tmp_9_fu_528_p2 <= (sel_tmp7_fu_510_p2 or sel_tmp10_fu_522_p2);
    tmp_fu_398_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(indexReg_V_reg_860),64));
    tmp_s_fu_402_p2 <= "1" when (valid_V = ap_const_lv4_F) else "0";
    validArray_V_4_address0 <= tmp_reg_894(4 - 1 downto 0);

    validArray_V_4_ce0_assign_proc : process(m_axi_dram_V_BVALID, ap_CS_fsm_state16, isEvict_2_reg_933)
    begin
        if ((not(((m_axi_dram_V_BVALID = ap_const_logic_0) and (isEvict_2_reg_933 = ap_const_lv1_1))) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
            validArray_V_4_ce0 <= ap_const_logic_1;
        else 
            validArray_V_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    
    validArray_V_4_d0_proc : process(tempValid_V_2_reg_921, Hi_assign_cast_reg_937)
    variable result: std_logic_vector(0 downto 0);
    begin
        validArray_V_4_d0 <= tempValid_V_2_reg_921;
        if to_integer(unsigned(Hi_assign_cast_reg_937)) >= tempValid_V_2_reg_921'low and to_integer(unsigned(Hi_assign_cast_reg_937)) <= tempValid_V_2_reg_921'high then
            result(0) := '0';
            for i in ap_const_lv4_1'range loop
                result(0) := result(0) or ap_const_lv4_1(i);
            end loop;
            validArray_V_4_d0(to_integer(unsigned(Hi_assign_cast_reg_937))) <= result(0);
        end if;
    end process;


    validArray_V_4_we0_assign_proc : process(m_axi_dram_V_BVALID, ap_CS_fsm_state16, isEvict_2_reg_933)
    begin
        if ((not(((m_axi_dram_V_BVALID = ap_const_logic_0) and (isEvict_2_reg_933 = ap_const_lv1_1))) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
            validArray_V_4_we0 <= ap_const_logic_1;
        else 
            validArray_V_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
