// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "ReadHit.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic ReadHit::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic ReadHit::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> ReadHit::ap_ST_fsm_state1 = "1";
const sc_lv<3> ReadHit::ap_ST_fsm_state2 = "10";
const sc_lv<3> ReadHit::ap_ST_fsm_state3 = "100";
const sc_lv<32> ReadHit::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> ReadHit::ap_const_lv32_1 = "1";
const sc_lv<32> ReadHit::ap_const_lv32_2 = "10";
const sc_lv<1> ReadHit::ap_const_lv1_1 = "1";
const sc_lv<32> ReadHit::ap_const_lv32_7 = "111";
const sc_lv<32> ReadHit::ap_const_lv32_1F = "11111";
const sc_lv<32> ReadHit::ap_const_lv32_8 = "1000";
const sc_lv<32> ReadHit::ap_const_lv32_3 = "11";
const sc_lv<32> ReadHit::ap_const_lv32_4 = "100";
const sc_lv<32> ReadHit::ap_const_lv32_5 = "101";
const sc_lv<32> ReadHit::ap_const_lv32_6 = "110";
const sc_lv<3> ReadHit::ap_const_lv3_2 = "10";
const sc_lv<3> ReadHit::ap_const_lv3_1 = "1";
const sc_lv<3> ReadHit::ap_const_lv3_7 = "111";
const sc_lv<3> ReadHit::ap_const_lv3_0 = "000";
const sc_lv<3> ReadHit::ap_const_lv3_6 = "110";
const sc_lv<3> ReadHit::ap_const_lv3_5 = "101";
const sc_lv<3> ReadHit::ap_const_lv3_4 = "100";
const sc_lv<3> ReadHit::ap_const_lv3_3 = "11";
const sc_lv<8> ReadHit::ap_const_lv8_FF = "11111111";
const sc_lv<8> ReadHit::ap_const_lv8_0 = "00000000";
const sc_lv<8> ReadHit::ap_const_lv8_1 = "1";
const sc_lv<8> ReadHit::ap_const_lv8_2 = "10";
const sc_lv<8> ReadHit::ap_const_lv8_3 = "11";
const sc_lv<8> ReadHit::ap_const_lv8_4 = "100";
const sc_lv<8> ReadHit::ap_const_lv8_5 = "101";
const sc_lv<8> ReadHit::ap_const_lv8_6 = "110";
const sc_lv<8> ReadHit::ap_const_lv8_7 = "111";
const sc_lv<512> ReadHit::ap_const_lv512_lc_1 = "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const bool ReadHit::ap_const_boolean_1 = true;

ReadHit::ReadHit(sc_module_name name) : sc_module(name), mVcdFile(0) {
    PLRUCache_mux_83_512_2_1_U1 = new PLRUCache_mux_83_512_2_1<1,2,512,512,512,512,512,512,512,512,3,512>("PLRUCache_mux_83_512_2_1_U1");
    PLRUCache_mux_83_512_2_1_U1->clk(ap_clk);
    PLRUCache_mux_83_512_2_1_U1->reset(ap_rst);
    PLRUCache_mux_83_512_2_1_U1->din0(dataArray_0_V_q0);
    PLRUCache_mux_83_512_2_1_U1->din1(dataArray_1_V_q0);
    PLRUCache_mux_83_512_2_1_U1->din2(dataArray_2_V_q0);
    PLRUCache_mux_83_512_2_1_U1->din3(dataArray_3_V_q0);
    PLRUCache_mux_83_512_2_1_U1->din4(dataArray_4_V_q0);
    PLRUCache_mux_83_512_2_1_U1->din5(dataArray_5_V_q0);
    PLRUCache_mux_83_512_2_1_U1->din6(dataArray_6_V_q0);
    PLRUCache_mux_83_512_2_1_U1->din7(dataArray_7_V_q0);
    PLRUCache_mux_83_512_2_1_U1->din8(grp_fu_656_p9);
    PLRUCache_mux_83_512_2_1_U1->ce(ap_var_for_const0);
    PLRUCache_mux_83_512_2_1_U1->dout(grp_fu_656_p10);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_clk_pos_reset_);
    dont_initialize();
    sensitive << ( ap_rst.pos() );
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( grp_fu_656_p10 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_dataArray_0_V_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_fu_308_p1 );

    SC_METHOD(thread_dataArray_0_V_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_dataArray_1_V_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_fu_308_p1 );

    SC_METHOD(thread_dataArray_1_V_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_dataArray_2_V_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_fu_308_p1 );

    SC_METHOD(thread_dataArray_2_V_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_dataArray_3_V_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_fu_308_p1 );

    SC_METHOD(thread_dataArray_3_V_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_dataArray_4_V_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_fu_308_p1 );

    SC_METHOD(thread_dataArray_4_V_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_dataArray_5_V_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_fu_308_p1 );

    SC_METHOD(thread_dataArray_5_V_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_dataArray_6_V_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_fu_308_p1 );

    SC_METHOD(thread_dataArray_6_V_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_dataArray_7_V_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_fu_308_p1 );

    SC_METHOD(thread_dataArray_7_V_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_grp_fu_656_p9);
    sensitive << ( newSel4_reg_794 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( or_cond3_fu_643_p2 );
    sensitive << ( newSel3_fu_635_p3 );

    SC_METHOD(thread_indexReg_V_fu_288_p4);
    sensitive << ( i_addr_V );

    SC_METHOD(thread_mruArray_V_6_address0);
    sensitive << ( mruArray_V_5_addr_reg_757 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_mruArray_V_6_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_mruArray_V_6_d0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( val_assign_7_fu_719_p2 );
    sensitive << ( val_assign_6_fu_714_p2 );
    sensitive << ( val_assign_5_fu_709_p2 );
    sensitive << ( val_assign_4_fu_704_p2 );
    sensitive << ( val_assign_3_fu_699_p2 );
    sensitive << ( val_assign_2_fu_694_p2 );
    sensitive << ( val_assign_1_fu_689_p2 );
    sensitive << ( val_assign_fu_684_p2 );

    SC_METHOD(thread_mruArray_V_6_we0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_s_fu_678_p2 );

    SC_METHOD(thread_newSel1_fu_623_p3);
    sensitive << ( sel_tmp15_reg_777 );

    SC_METHOD(thread_newSel2_fu_569_p2);
    sensitive << ( sel_tmp1_fu_471_p2 );
    sensitive << ( or_cond3_49_fu_465_p2 );

    SC_METHOD(thread_newSel3_fu_635_p3);
    sensitive << ( or_cond_fu_618_p2 );
    sensitive << ( newSel_fu_611_p3 );
    sensitive << ( newSel1_fu_623_p3 );

    SC_METHOD(thread_newSel4_fu_583_p3);
    sensitive << ( or_cond2_fu_563_p2 );
    sensitive << ( newSel52_cast_cast_fu_555_p3 );
    sensitive << ( newSel54_cast_fu_575_p3 );

    SC_METHOD(thread_newSel52_cast_cast_fu_555_p3);
    sensitive << ( sel_tmp7_fu_495_p2 );

    SC_METHOD(thread_newSel54_cast_fu_575_p3);
    sensitive << ( newSel2_fu_569_p2 );

    SC_METHOD(thread_newSel_fu_611_p3);
    sensitive << ( sel_tmp19_reg_788 );

    SC_METHOD(thread_or_cond1_48_fu_431_p2);
    sensitive << ( tmp_59_fu_417_p3 );
    sensitive << ( tmp_26_5_fu_425_p2 );

    SC_METHOD(thread_or_cond1_fu_630_p2);
    sensitive << ( sel_tmp15_reg_777 );
    sensitive << ( sel_tmp14_fu_596_p2 );

    SC_METHOD(thread_or_cond2_fu_563_p2);
    sensitive << ( sel_tmp7_fu_495_p2 );
    sensitive << ( sel_tmp2_fu_477_p2 );

    SC_METHOD(thread_or_cond3_49_fu_465_p2);
    sensitive << ( tmp_61_fu_451_p3 );
    sensitive << ( tmp_26_7_fu_459_p2 );

    SC_METHOD(thread_or_cond3_fu_643_p2);
    sensitive << ( or_cond_fu_618_p2 );
    sensitive << ( or_cond1_fu_630_p2 );

    SC_METHOD(thread_or_cond6_fu_391_p2);
    sensitive << ( tmp_57_fu_377_p3 );
    sensitive << ( tmp_26_3_fu_385_p2 );

    SC_METHOD(thread_or_cond7_fu_411_p2);
    sensitive << ( tmp_58_fu_397_p3 );
    sensitive << ( tmp_26_4_fu_405_p2 );

    SC_METHOD(thread_or_cond8_fu_351_p2);
    sensitive << ( tmp_55_fu_337_p3 );
    sensitive << ( tmp_26_1_fu_345_p2 );

    SC_METHOD(thread_or_cond9_fu_371_p2);
    sensitive << ( tmp_56_fu_357_p3 );
    sensitive << ( tmp_26_2_fu_365_p2 );

    SC_METHOD(thread_or_cond_47_fu_331_p2);
    sensitive << ( tmp_54_fu_321_p1 );
    sensitive << ( tmp_2_fu_325_p2 );

    SC_METHOD(thread_or_cond_fu_618_p2);
    sensitive << ( sel_tmp19_reg_788 );
    sensitive << ( sel_tmp17_fu_606_p2 );

    SC_METHOD(thread_sel_tmp13_demorgan_fu_501_p2);
    sensitive << ( sel_tmp6_demorgan_fu_483_p2 );
    sensitive << ( or_cond9_fu_371_p2 );

    SC_METHOD(thread_sel_tmp13_fu_591_p2);
    sensitive << ( sel_tmp13_demorgan_reg_772 );

    SC_METHOD(thread_sel_tmp14_fu_596_p2);
    sensitive << ( or_cond6_reg_762 );
    sensitive << ( sel_tmp13_fu_591_p2 );

    SC_METHOD(thread_sel_tmp15_fu_519_p2);
    sensitive << ( or_cond7_fu_411_p2 );
    sensitive << ( sel_tmp_fu_513_p2 );

    SC_METHOD(thread_sel_tmp16_fu_601_p2);
    sensitive << ( sel_tmp33_demorgan_reg_783 );

    SC_METHOD(thread_sel_tmp17_fu_606_p2);
    sensitive << ( or_cond1_48_reg_767 );
    sensitive << ( sel_tmp16_fu_601_p2 );

    SC_METHOD(thread_sel_tmp18_fu_537_p2);
    sensitive << ( sel_tmp46_demorgan_fu_531_p2 );

    SC_METHOD(thread_sel_tmp19_fu_549_p2);
    sensitive << ( tmp1_fu_543_p2 );
    sensitive << ( tmp_60_fu_437_p3 );

    SC_METHOD(thread_sel_tmp1_fu_471_p2);
    sensitive << ( or_cond_47_fu_331_p2 );

    SC_METHOD(thread_sel_tmp22_demorgan_fu_507_p2);
    sensitive << ( or_cond6_fu_391_p2 );
    sensitive << ( sel_tmp13_demorgan_fu_501_p2 );

    SC_METHOD(thread_sel_tmp2_fu_477_p2);
    sensitive << ( or_cond8_fu_351_p2 );
    sensitive << ( sel_tmp1_fu_471_p2 );

    SC_METHOD(thread_sel_tmp33_demorgan_fu_525_p2);
    sensitive << ( sel_tmp22_demorgan_fu_507_p2 );
    sensitive << ( or_cond7_fu_411_p2 );

    SC_METHOD(thread_sel_tmp46_demorgan_fu_531_p2);
    sensitive << ( or_cond1_48_fu_431_p2 );
    sensitive << ( sel_tmp33_demorgan_fu_525_p2 );

    SC_METHOD(thread_sel_tmp6_demorgan_fu_483_p2);
    sensitive << ( or_cond_47_fu_331_p2 );
    sensitive << ( or_cond8_fu_351_p2 );

    SC_METHOD(thread_sel_tmp6_fu_489_p2);
    sensitive << ( sel_tmp6_demorgan_fu_483_p2 );

    SC_METHOD(thread_sel_tmp7_fu_495_p2);
    sensitive << ( or_cond9_fu_371_p2 );
    sensitive << ( sel_tmp6_fu_489_p2 );

    SC_METHOD(thread_sel_tmp_fu_513_p2);
    sensitive << ( sel_tmp22_demorgan_fu_507_p2 );

    SC_METHOD(thread_tagReg_V_fu_298_p4);
    sensitive << ( i_addr_V );

    SC_METHOD(thread_tmp1_fu_543_p2);
    sensitive << ( tmp_26_6_fu_445_p2 );
    sensitive << ( sel_tmp18_fu_537_p2 );

    SC_METHOD(thread_tmp_26_1_fu_345_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tag_1_V_read );
    sensitive << ( tagReg_V_fu_298_p4 );

    SC_METHOD(thread_tmp_26_2_fu_365_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tag_2_V_read );
    sensitive << ( tagReg_V_fu_298_p4 );

    SC_METHOD(thread_tmp_26_3_fu_385_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tag_3_V_read );
    sensitive << ( tagReg_V_fu_298_p4 );

    SC_METHOD(thread_tmp_26_4_fu_405_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tag_4_V_read );
    sensitive << ( tagReg_V_fu_298_p4 );

    SC_METHOD(thread_tmp_26_5_fu_425_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tag_5_V_read );
    sensitive << ( tagReg_V_fu_298_p4 );

    SC_METHOD(thread_tmp_26_6_fu_445_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tag_6_V_read );
    sensitive << ( tagReg_V_fu_298_p4 );

    SC_METHOD(thread_tmp_26_7_fu_459_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tag_7_V_read );
    sensitive << ( tagReg_V_fu_298_p4 );

    SC_METHOD(thread_tmp_2_fu_325_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tag_0_V_read );
    sensitive << ( tagReg_V_fu_298_p4 );

    SC_METHOD(thread_tmp_54_fu_321_p1);
    sensitive << ( valid_V );

    SC_METHOD(thread_tmp_55_fu_337_p3);
    sensitive << ( valid_V );

    SC_METHOD(thread_tmp_56_fu_357_p3);
    sensitive << ( valid_V );

    SC_METHOD(thread_tmp_57_fu_377_p3);
    sensitive << ( valid_V );

    SC_METHOD(thread_tmp_58_fu_397_p3);
    sensitive << ( valid_V );

    SC_METHOD(thread_tmp_59_fu_417_p3);
    sensitive << ( valid_V );

    SC_METHOD(thread_tmp_60_fu_437_p3);
    sensitive << ( valid_V );

    SC_METHOD(thread_tmp_61_fu_451_p3);
    sensitive << ( valid_V );

    SC_METHOD(thread_tmp_fu_308_p1);
    sensitive << ( indexReg_V_fu_288_p4 );

    SC_METHOD(thread_tmp_s_fu_678_p2);
    sensitive << ( mruArray_V_6_q0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_val_assign_1_fu_689_p2);
    sensitive << ( indexReg_V_reg_745 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_s_fu_678_p2 );

    SC_METHOD(thread_val_assign_2_fu_694_p2);
    sensitive << ( indexReg_V_reg_745 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_s_fu_678_p2 );

    SC_METHOD(thread_val_assign_3_fu_699_p2);
    sensitive << ( indexReg_V_reg_745 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_s_fu_678_p2 );

    SC_METHOD(thread_val_assign_4_fu_704_p2);
    sensitive << ( indexReg_V_reg_745 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_s_fu_678_p2 );

    SC_METHOD(thread_val_assign_5_fu_709_p2);
    sensitive << ( indexReg_V_reg_745 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_s_fu_678_p2 );

    SC_METHOD(thread_val_assign_6_fu_714_p2);
    sensitive << ( indexReg_V_reg_745 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_s_fu_678_p2 );

    SC_METHOD(thread_val_assign_7_fu_719_p2);
    sensitive << ( indexReg_V_reg_745 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_s_fu_678_p2 );

    SC_METHOD(thread_val_assign_fu_684_p2);
    sensitive << ( indexReg_V_reg_745 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_s_fu_678_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "001";
    ap_return_preg = "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "ReadHit_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, i_addr_V, "(port)i_addr_V");
    sc_trace(mVcdFile, valid_V, "(port)valid_V");
    sc_trace(mVcdFile, tag_0_V_read, "(port)tag_0_V_read");
    sc_trace(mVcdFile, tag_1_V_read, "(port)tag_1_V_read");
    sc_trace(mVcdFile, tag_2_V_read, "(port)tag_2_V_read");
    sc_trace(mVcdFile, tag_3_V_read, "(port)tag_3_V_read");
    sc_trace(mVcdFile, tag_4_V_read, "(port)tag_4_V_read");
    sc_trace(mVcdFile, tag_5_V_read, "(port)tag_5_V_read");
    sc_trace(mVcdFile, tag_6_V_read, "(port)tag_6_V_read");
    sc_trace(mVcdFile, tag_7_V_read, "(port)tag_7_V_read");
    sc_trace(mVcdFile, dataArray_0_V_address0, "(port)dataArray_0_V_address0");
    sc_trace(mVcdFile, dataArray_0_V_ce0, "(port)dataArray_0_V_ce0");
    sc_trace(mVcdFile, dataArray_0_V_q0, "(port)dataArray_0_V_q0");
    sc_trace(mVcdFile, dataArray_1_V_address0, "(port)dataArray_1_V_address0");
    sc_trace(mVcdFile, dataArray_1_V_ce0, "(port)dataArray_1_V_ce0");
    sc_trace(mVcdFile, dataArray_1_V_q0, "(port)dataArray_1_V_q0");
    sc_trace(mVcdFile, dataArray_2_V_address0, "(port)dataArray_2_V_address0");
    sc_trace(mVcdFile, dataArray_2_V_ce0, "(port)dataArray_2_V_ce0");
    sc_trace(mVcdFile, dataArray_2_V_q0, "(port)dataArray_2_V_q0");
    sc_trace(mVcdFile, dataArray_3_V_address0, "(port)dataArray_3_V_address0");
    sc_trace(mVcdFile, dataArray_3_V_ce0, "(port)dataArray_3_V_ce0");
    sc_trace(mVcdFile, dataArray_3_V_q0, "(port)dataArray_3_V_q0");
    sc_trace(mVcdFile, dataArray_4_V_address0, "(port)dataArray_4_V_address0");
    sc_trace(mVcdFile, dataArray_4_V_ce0, "(port)dataArray_4_V_ce0");
    sc_trace(mVcdFile, dataArray_4_V_q0, "(port)dataArray_4_V_q0");
    sc_trace(mVcdFile, dataArray_5_V_address0, "(port)dataArray_5_V_address0");
    sc_trace(mVcdFile, dataArray_5_V_ce0, "(port)dataArray_5_V_ce0");
    sc_trace(mVcdFile, dataArray_5_V_q0, "(port)dataArray_5_V_q0");
    sc_trace(mVcdFile, dataArray_6_V_address0, "(port)dataArray_6_V_address0");
    sc_trace(mVcdFile, dataArray_6_V_ce0, "(port)dataArray_6_V_ce0");
    sc_trace(mVcdFile, dataArray_6_V_q0, "(port)dataArray_6_V_q0");
    sc_trace(mVcdFile, dataArray_7_V_address0, "(port)dataArray_7_V_address0");
    sc_trace(mVcdFile, dataArray_7_V_ce0, "(port)dataArray_7_V_ce0");
    sc_trace(mVcdFile, dataArray_7_V_q0, "(port)dataArray_7_V_q0");
    sc_trace(mVcdFile, mruArray_V_6_address0, "(port)mruArray_V_6_address0");
    sc_trace(mVcdFile, mruArray_V_6_ce0, "(port)mruArray_V_6_ce0");
    sc_trace(mVcdFile, mruArray_V_6_we0, "(port)mruArray_V_6_we0");
    sc_trace(mVcdFile, mruArray_V_6_d0, "(port)mruArray_V_6_d0");
    sc_trace(mVcdFile, mruArray_V_6_q0, "(port)mruArray_V_6_q0");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, indexReg_V_fu_288_p4, "indexReg_V_fu_288_p4");
    sc_trace(mVcdFile, indexReg_V_reg_745, "indexReg_V_reg_745");
    sc_trace(mVcdFile, mruArray_V_5_addr_reg_757, "mruArray_V_5_addr_reg_757");
    sc_trace(mVcdFile, or_cond6_fu_391_p2, "or_cond6_fu_391_p2");
    sc_trace(mVcdFile, or_cond6_reg_762, "or_cond6_reg_762");
    sc_trace(mVcdFile, or_cond1_48_fu_431_p2, "or_cond1_48_fu_431_p2");
    sc_trace(mVcdFile, or_cond1_48_reg_767, "or_cond1_48_reg_767");
    sc_trace(mVcdFile, sel_tmp13_demorgan_fu_501_p2, "sel_tmp13_demorgan_fu_501_p2");
    sc_trace(mVcdFile, sel_tmp13_demorgan_reg_772, "sel_tmp13_demorgan_reg_772");
    sc_trace(mVcdFile, sel_tmp15_fu_519_p2, "sel_tmp15_fu_519_p2");
    sc_trace(mVcdFile, sel_tmp15_reg_777, "sel_tmp15_reg_777");
    sc_trace(mVcdFile, sel_tmp33_demorgan_fu_525_p2, "sel_tmp33_demorgan_fu_525_p2");
    sc_trace(mVcdFile, sel_tmp33_demorgan_reg_783, "sel_tmp33_demorgan_reg_783");
    sc_trace(mVcdFile, sel_tmp19_fu_549_p2, "sel_tmp19_fu_549_p2");
    sc_trace(mVcdFile, sel_tmp19_reg_788, "sel_tmp19_reg_788");
    sc_trace(mVcdFile, newSel4_fu_583_p3, "newSel4_fu_583_p3");
    sc_trace(mVcdFile, newSel4_reg_794, "newSel4_reg_794");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_fu_308_p1, "tmp_fu_308_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_s_fu_678_p2, "tmp_s_fu_678_p2");
    sc_trace(mVcdFile, tagReg_V_fu_298_p4, "tagReg_V_fu_298_p4");
    sc_trace(mVcdFile, tmp_54_fu_321_p1, "tmp_54_fu_321_p1");
    sc_trace(mVcdFile, tmp_2_fu_325_p2, "tmp_2_fu_325_p2");
    sc_trace(mVcdFile, tmp_55_fu_337_p3, "tmp_55_fu_337_p3");
    sc_trace(mVcdFile, tmp_26_1_fu_345_p2, "tmp_26_1_fu_345_p2");
    sc_trace(mVcdFile, tmp_56_fu_357_p3, "tmp_56_fu_357_p3");
    sc_trace(mVcdFile, tmp_26_2_fu_365_p2, "tmp_26_2_fu_365_p2");
    sc_trace(mVcdFile, tmp_57_fu_377_p3, "tmp_57_fu_377_p3");
    sc_trace(mVcdFile, tmp_26_3_fu_385_p2, "tmp_26_3_fu_385_p2");
    sc_trace(mVcdFile, tmp_58_fu_397_p3, "tmp_58_fu_397_p3");
    sc_trace(mVcdFile, tmp_26_4_fu_405_p2, "tmp_26_4_fu_405_p2");
    sc_trace(mVcdFile, tmp_59_fu_417_p3, "tmp_59_fu_417_p3");
    sc_trace(mVcdFile, tmp_26_5_fu_425_p2, "tmp_26_5_fu_425_p2");
    sc_trace(mVcdFile, tmp_61_fu_451_p3, "tmp_61_fu_451_p3");
    sc_trace(mVcdFile, tmp_26_7_fu_459_p2, "tmp_26_7_fu_459_p2");
    sc_trace(mVcdFile, or_cond_47_fu_331_p2, "or_cond_47_fu_331_p2");
    sc_trace(mVcdFile, or_cond8_fu_351_p2, "or_cond8_fu_351_p2");
    sc_trace(mVcdFile, sel_tmp1_fu_471_p2, "sel_tmp1_fu_471_p2");
    sc_trace(mVcdFile, sel_tmp6_demorgan_fu_483_p2, "sel_tmp6_demorgan_fu_483_p2");
    sc_trace(mVcdFile, or_cond9_fu_371_p2, "or_cond9_fu_371_p2");
    sc_trace(mVcdFile, sel_tmp6_fu_489_p2, "sel_tmp6_fu_489_p2");
    sc_trace(mVcdFile, sel_tmp22_demorgan_fu_507_p2, "sel_tmp22_demorgan_fu_507_p2");
    sc_trace(mVcdFile, or_cond7_fu_411_p2, "or_cond7_fu_411_p2");
    sc_trace(mVcdFile, sel_tmp_fu_513_p2, "sel_tmp_fu_513_p2");
    sc_trace(mVcdFile, sel_tmp46_demorgan_fu_531_p2, "sel_tmp46_demorgan_fu_531_p2");
    sc_trace(mVcdFile, tmp_26_6_fu_445_p2, "tmp_26_6_fu_445_p2");
    sc_trace(mVcdFile, sel_tmp18_fu_537_p2, "sel_tmp18_fu_537_p2");
    sc_trace(mVcdFile, tmp1_fu_543_p2, "tmp1_fu_543_p2");
    sc_trace(mVcdFile, tmp_60_fu_437_p3, "tmp_60_fu_437_p3");
    sc_trace(mVcdFile, sel_tmp7_fu_495_p2, "sel_tmp7_fu_495_p2");
    sc_trace(mVcdFile, sel_tmp2_fu_477_p2, "sel_tmp2_fu_477_p2");
    sc_trace(mVcdFile, or_cond3_49_fu_465_p2, "or_cond3_49_fu_465_p2");
    sc_trace(mVcdFile, newSel2_fu_569_p2, "newSel2_fu_569_p2");
    sc_trace(mVcdFile, or_cond2_fu_563_p2, "or_cond2_fu_563_p2");
    sc_trace(mVcdFile, newSel52_cast_cast_fu_555_p3, "newSel52_cast_cast_fu_555_p3");
    sc_trace(mVcdFile, newSel54_cast_fu_575_p3, "newSel54_cast_fu_575_p3");
    sc_trace(mVcdFile, sel_tmp13_fu_591_p2, "sel_tmp13_fu_591_p2");
    sc_trace(mVcdFile, sel_tmp16_fu_601_p2, "sel_tmp16_fu_601_p2");
    sc_trace(mVcdFile, sel_tmp17_fu_606_p2, "sel_tmp17_fu_606_p2");
    sc_trace(mVcdFile, sel_tmp14_fu_596_p2, "sel_tmp14_fu_596_p2");
    sc_trace(mVcdFile, or_cond_fu_618_p2, "or_cond_fu_618_p2");
    sc_trace(mVcdFile, newSel_fu_611_p3, "newSel_fu_611_p3");
    sc_trace(mVcdFile, newSel1_fu_623_p3, "newSel1_fu_623_p3");
    sc_trace(mVcdFile, or_cond1_fu_630_p2, "or_cond1_fu_630_p2");
    sc_trace(mVcdFile, or_cond3_fu_643_p2, "or_cond3_fu_643_p2");
    sc_trace(mVcdFile, newSel3_fu_635_p3, "newSel3_fu_635_p3");
    sc_trace(mVcdFile, grp_fu_656_p9, "grp_fu_656_p9");
    sc_trace(mVcdFile, val_assign_7_fu_719_p2, "val_assign_7_fu_719_p2");
    sc_trace(mVcdFile, val_assign_6_fu_714_p2, "val_assign_6_fu_714_p2");
    sc_trace(mVcdFile, val_assign_5_fu_709_p2, "val_assign_5_fu_709_p2");
    sc_trace(mVcdFile, val_assign_4_fu_704_p2, "val_assign_4_fu_704_p2");
    sc_trace(mVcdFile, val_assign_3_fu_699_p2, "val_assign_3_fu_699_p2");
    sc_trace(mVcdFile, val_assign_2_fu_694_p2, "val_assign_2_fu_694_p2");
    sc_trace(mVcdFile, val_assign_1_fu_689_p2, "val_assign_1_fu_689_p2");
    sc_trace(mVcdFile, val_assign_fu_684_p2, "val_assign_fu_684_p2");
    sc_trace(mVcdFile, grp_fu_656_p10, "grp_fu_656_p10");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

ReadHit::~ReadHit() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete PLRUCache_mux_83_512_2_1_U1;
}

void ReadHit::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void ReadHit::thread_ap_clk_no_reset_() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indexReg_V_reg_745 = indexReg_V_fu_288_p4.read();
        mruArray_V_5_addr_reg_757 =  (sc_lv<8>) (tmp_fu_308_p1.read());
        newSel4_reg_794 = newSel4_fu_583_p3.read();
        or_cond1_48_reg_767 = or_cond1_48_fu_431_p2.read();
        or_cond6_reg_762 = or_cond6_fu_391_p2.read();
        sel_tmp13_demorgan_reg_772 = sel_tmp13_demorgan_fu_501_p2.read();
        sel_tmp15_reg_777 = sel_tmp15_fu_519_p2.read();
        sel_tmp19_reg_788 = sel_tmp19_fu_549_p2.read();
        sel_tmp33_demorgan_reg_783 = sel_tmp33_demorgan_fu_525_p2.read();
    }
}

void ReadHit::thread_ap_clk_pos_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv512_lc_1;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
            ap_return_preg = grp_fu_656_p10.read();
        }
    }
}

void ReadHit::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void ReadHit::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void ReadHit::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void ReadHit::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void ReadHit::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void ReadHit::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void ReadHit::thread_ap_return() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        ap_return = grp_fu_656_p10.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void ReadHit::thread_dataArray_0_V_address0() {
    dataArray_0_V_address0 =  (sc_lv<8>) (tmp_fu_308_p1.read());
}

void ReadHit::thread_dataArray_0_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        dataArray_0_V_ce0 = ap_const_logic_1;
    } else {
        dataArray_0_V_ce0 = ap_const_logic_0;
    }
}

void ReadHit::thread_dataArray_1_V_address0() {
    dataArray_1_V_address0 =  (sc_lv<8>) (tmp_fu_308_p1.read());
}

void ReadHit::thread_dataArray_1_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        dataArray_1_V_ce0 = ap_const_logic_1;
    } else {
        dataArray_1_V_ce0 = ap_const_logic_0;
    }
}

void ReadHit::thread_dataArray_2_V_address0() {
    dataArray_2_V_address0 =  (sc_lv<8>) (tmp_fu_308_p1.read());
}

void ReadHit::thread_dataArray_2_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        dataArray_2_V_ce0 = ap_const_logic_1;
    } else {
        dataArray_2_V_ce0 = ap_const_logic_0;
    }
}

void ReadHit::thread_dataArray_3_V_address0() {
    dataArray_3_V_address0 =  (sc_lv<8>) (tmp_fu_308_p1.read());
}

void ReadHit::thread_dataArray_3_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        dataArray_3_V_ce0 = ap_const_logic_1;
    } else {
        dataArray_3_V_ce0 = ap_const_logic_0;
    }
}

void ReadHit::thread_dataArray_4_V_address0() {
    dataArray_4_V_address0 =  (sc_lv<8>) (tmp_fu_308_p1.read());
}

void ReadHit::thread_dataArray_4_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        dataArray_4_V_ce0 = ap_const_logic_1;
    } else {
        dataArray_4_V_ce0 = ap_const_logic_0;
    }
}

void ReadHit::thread_dataArray_5_V_address0() {
    dataArray_5_V_address0 =  (sc_lv<8>) (tmp_fu_308_p1.read());
}

void ReadHit::thread_dataArray_5_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        dataArray_5_V_ce0 = ap_const_logic_1;
    } else {
        dataArray_5_V_ce0 = ap_const_logic_0;
    }
}

void ReadHit::thread_dataArray_6_V_address0() {
    dataArray_6_V_address0 =  (sc_lv<8>) (tmp_fu_308_p1.read());
}

void ReadHit::thread_dataArray_6_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        dataArray_6_V_ce0 = ap_const_logic_1;
    } else {
        dataArray_6_V_ce0 = ap_const_logic_0;
    }
}

void ReadHit::thread_dataArray_7_V_address0() {
    dataArray_7_V_address0 =  (sc_lv<8>) (tmp_fu_308_p1.read());
}

void ReadHit::thread_dataArray_7_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        dataArray_7_V_ce0 = ap_const_logic_1;
    } else {
        dataArray_7_V_ce0 = ap_const_logic_0;
    }
}

void ReadHit::thread_grp_fu_656_p9() {
    grp_fu_656_p9 = (!or_cond3_fu_643_p2.read()[0].is_01())? sc_lv<3>(): ((or_cond3_fu_643_p2.read()[0].to_bool())? newSel3_fu_635_p3.read(): newSel4_reg_794.read());
}

void ReadHit::thread_indexReg_V_fu_288_p4() {
    indexReg_V_fu_288_p4 = i_addr_V.read().range(0, 7);
}

void ReadHit::thread_mruArray_V_6_address0() {
    mruArray_V_6_address0 = mruArray_V_5_addr_reg_757.read();
}

void ReadHit::thread_mruArray_V_6_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        mruArray_V_6_ce0 = ap_const_logic_1;
    } else {
        mruArray_V_6_ce0 = ap_const_logic_0;
    }
}

void ReadHit::thread_mruArray_V_6_d0() {
    mruArray_V_6_d0 = esl_concat<7,1>(esl_concat<6,1>(esl_concat<5,1>(esl_concat<4,1>(esl_concat<3,1>(esl_concat<2,1>(esl_concat<1,1>(val_assign_7_fu_719_p2.read(), val_assign_6_fu_714_p2.read()), val_assign_5_fu_709_p2.read()), val_assign_4_fu_704_p2.read()), val_assign_3_fu_699_p2.read()), val_assign_2_fu_694_p2.read()), val_assign_1_fu_689_p2.read()), val_assign_fu_684_p2.read());
}

void ReadHit::thread_mruArray_V_6_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(tmp_s_fu_678_p2.read(), ap_const_lv1_1))) {
        mruArray_V_6_we0 = ap_const_logic_1;
    } else {
        mruArray_V_6_we0 = ap_const_logic_0;
    }
}

void ReadHit::thread_newSel1_fu_623_p3() {
    newSel1_fu_623_p3 = (!sel_tmp15_reg_777.read()[0].is_01())? sc_lv<3>(): ((sel_tmp15_reg_777.read()[0].to_bool())? ap_const_lv3_4: ap_const_lv3_3);
}

void ReadHit::thread_newSel2_fu_569_p2() {
    newSel2_fu_569_p2 = (or_cond3_49_fu_465_p2.read() & sel_tmp1_fu_471_p2.read());
}

void ReadHit::thread_newSel3_fu_635_p3() {
    newSel3_fu_635_p3 = (!or_cond_fu_618_p2.read()[0].is_01())? sc_lv<3>(): ((or_cond_fu_618_p2.read()[0].to_bool())? newSel_fu_611_p3.read(): newSel1_fu_623_p3.read());
}

void ReadHit::thread_newSel4_fu_583_p3() {
    newSel4_fu_583_p3 = (!or_cond2_fu_563_p2.read()[0].is_01())? sc_lv<3>(): ((or_cond2_fu_563_p2.read()[0].to_bool())? newSel52_cast_cast_fu_555_p3.read(): newSel54_cast_fu_575_p3.read());
}

void ReadHit::thread_newSel52_cast_cast_fu_555_p3() {
    newSel52_cast_cast_fu_555_p3 = (!sel_tmp7_fu_495_p2.read()[0].is_01())? sc_lv<3>(): ((sel_tmp7_fu_495_p2.read()[0].to_bool())? ap_const_lv3_2: ap_const_lv3_1);
}

void ReadHit::thread_newSel54_cast_fu_575_p3() {
    newSel54_cast_fu_575_p3 = (!newSel2_fu_569_p2.read()[0].is_01())? sc_lv<3>(): ((newSel2_fu_569_p2.read()[0].to_bool())? ap_const_lv3_7: ap_const_lv3_0);
}

void ReadHit::thread_newSel_fu_611_p3() {
    newSel_fu_611_p3 = (!sel_tmp19_reg_788.read()[0].is_01())? sc_lv<3>(): ((sel_tmp19_reg_788.read()[0].to_bool())? ap_const_lv3_6: ap_const_lv3_5);
}

void ReadHit::thread_or_cond1_48_fu_431_p2() {
    or_cond1_48_fu_431_p2 = (tmp_59_fu_417_p3.read() & tmp_26_5_fu_425_p2.read());
}

void ReadHit::thread_or_cond1_fu_630_p2() {
    or_cond1_fu_630_p2 = (sel_tmp15_reg_777.read() | sel_tmp14_fu_596_p2.read());
}

void ReadHit::thread_or_cond2_fu_563_p2() {
    or_cond2_fu_563_p2 = (sel_tmp7_fu_495_p2.read() | sel_tmp2_fu_477_p2.read());
}

void ReadHit::thread_or_cond3_49_fu_465_p2() {
    or_cond3_49_fu_465_p2 = (tmp_61_fu_451_p3.read() & tmp_26_7_fu_459_p2.read());
}

void ReadHit::thread_or_cond3_fu_643_p2() {
    or_cond3_fu_643_p2 = (or_cond_fu_618_p2.read() | or_cond1_fu_630_p2.read());
}

void ReadHit::thread_or_cond6_fu_391_p2() {
    or_cond6_fu_391_p2 = (tmp_57_fu_377_p3.read() & tmp_26_3_fu_385_p2.read());
}

void ReadHit::thread_or_cond7_fu_411_p2() {
    or_cond7_fu_411_p2 = (tmp_58_fu_397_p3.read() & tmp_26_4_fu_405_p2.read());
}

void ReadHit::thread_or_cond8_fu_351_p2() {
    or_cond8_fu_351_p2 = (tmp_55_fu_337_p3.read() & tmp_26_1_fu_345_p2.read());
}

void ReadHit::thread_or_cond9_fu_371_p2() {
    or_cond9_fu_371_p2 = (tmp_56_fu_357_p3.read() & tmp_26_2_fu_365_p2.read());
}

void ReadHit::thread_or_cond_47_fu_331_p2() {
    or_cond_47_fu_331_p2 = (tmp_54_fu_321_p1.read() & tmp_2_fu_325_p2.read());
}

void ReadHit::thread_or_cond_fu_618_p2() {
    or_cond_fu_618_p2 = (sel_tmp19_reg_788.read() | sel_tmp17_fu_606_p2.read());
}

void ReadHit::thread_sel_tmp13_demorgan_fu_501_p2() {
    sel_tmp13_demorgan_fu_501_p2 = (sel_tmp6_demorgan_fu_483_p2.read() | or_cond9_fu_371_p2.read());
}

void ReadHit::thread_sel_tmp13_fu_591_p2() {
    sel_tmp13_fu_591_p2 = (sel_tmp13_demorgan_reg_772.read() ^ ap_const_lv1_1);
}

void ReadHit::thread_sel_tmp14_fu_596_p2() {
    sel_tmp14_fu_596_p2 = (or_cond6_reg_762.read() & sel_tmp13_fu_591_p2.read());
}

void ReadHit::thread_sel_tmp15_fu_519_p2() {
    sel_tmp15_fu_519_p2 = (or_cond7_fu_411_p2.read() & sel_tmp_fu_513_p2.read());
}

void ReadHit::thread_sel_tmp16_fu_601_p2() {
    sel_tmp16_fu_601_p2 = (sel_tmp33_demorgan_reg_783.read() ^ ap_const_lv1_1);
}

void ReadHit::thread_sel_tmp17_fu_606_p2() {
    sel_tmp17_fu_606_p2 = (or_cond1_48_reg_767.read() & sel_tmp16_fu_601_p2.read());
}

void ReadHit::thread_sel_tmp18_fu_537_p2() {
    sel_tmp18_fu_537_p2 = (sel_tmp46_demorgan_fu_531_p2.read() ^ ap_const_lv1_1);
}

void ReadHit::thread_sel_tmp19_fu_549_p2() {
    sel_tmp19_fu_549_p2 = (tmp1_fu_543_p2.read() & tmp_60_fu_437_p3.read());
}

void ReadHit::thread_sel_tmp1_fu_471_p2() {
    sel_tmp1_fu_471_p2 = (or_cond_47_fu_331_p2.read() ^ ap_const_lv1_1);
}

void ReadHit::thread_sel_tmp22_demorgan_fu_507_p2() {
    sel_tmp22_demorgan_fu_507_p2 = (sel_tmp13_demorgan_fu_501_p2.read() | or_cond6_fu_391_p2.read());
}

void ReadHit::thread_sel_tmp2_fu_477_p2() {
    sel_tmp2_fu_477_p2 = (or_cond8_fu_351_p2.read() & sel_tmp1_fu_471_p2.read());
}

void ReadHit::thread_sel_tmp33_demorgan_fu_525_p2() {
    sel_tmp33_demorgan_fu_525_p2 = (sel_tmp22_demorgan_fu_507_p2.read() | or_cond7_fu_411_p2.read());
}

void ReadHit::thread_sel_tmp46_demorgan_fu_531_p2() {
    sel_tmp46_demorgan_fu_531_p2 = (sel_tmp33_demorgan_fu_525_p2.read() | or_cond1_48_fu_431_p2.read());
}

void ReadHit::thread_sel_tmp6_demorgan_fu_483_p2() {
    sel_tmp6_demorgan_fu_483_p2 = (or_cond_47_fu_331_p2.read() | or_cond8_fu_351_p2.read());
}

void ReadHit::thread_sel_tmp6_fu_489_p2() {
    sel_tmp6_fu_489_p2 = (sel_tmp6_demorgan_fu_483_p2.read() ^ ap_const_lv1_1);
}

void ReadHit::thread_sel_tmp7_fu_495_p2() {
    sel_tmp7_fu_495_p2 = (or_cond9_fu_371_p2.read() & sel_tmp6_fu_489_p2.read());
}

void ReadHit::thread_sel_tmp_fu_513_p2() {
    sel_tmp_fu_513_p2 = (sel_tmp22_demorgan_fu_507_p2.read() ^ ap_const_lv1_1);
}

void ReadHit::thread_tagReg_V_fu_298_p4() {
    tagReg_V_fu_298_p4 = i_addr_V.read().range(8, 31);
}

void ReadHit::thread_tmp1_fu_543_p2() {
    tmp1_fu_543_p2 = (tmp_26_6_fu_445_p2.read() & sel_tmp18_fu_537_p2.read());
}

void ReadHit::thread_tmp_26_1_fu_345_p2() {
    tmp_26_1_fu_345_p2 = (!tagReg_V_fu_298_p4.read().is_01() || !tag_1_V_read.read().is_01())? sc_lv<1>(): sc_lv<1>(tagReg_V_fu_298_p4.read() == tag_1_V_read.read());
}

void ReadHit::thread_tmp_26_2_fu_365_p2() {
    tmp_26_2_fu_365_p2 = (!tagReg_V_fu_298_p4.read().is_01() || !tag_2_V_read.read().is_01())? sc_lv<1>(): sc_lv<1>(tagReg_V_fu_298_p4.read() == tag_2_V_read.read());
}

void ReadHit::thread_tmp_26_3_fu_385_p2() {
    tmp_26_3_fu_385_p2 = (!tagReg_V_fu_298_p4.read().is_01() || !tag_3_V_read.read().is_01())? sc_lv<1>(): sc_lv<1>(tagReg_V_fu_298_p4.read() == tag_3_V_read.read());
}

void ReadHit::thread_tmp_26_4_fu_405_p2() {
    tmp_26_4_fu_405_p2 = (!tagReg_V_fu_298_p4.read().is_01() || !tag_4_V_read.read().is_01())? sc_lv<1>(): sc_lv<1>(tagReg_V_fu_298_p4.read() == tag_4_V_read.read());
}

void ReadHit::thread_tmp_26_5_fu_425_p2() {
    tmp_26_5_fu_425_p2 = (!tagReg_V_fu_298_p4.read().is_01() || !tag_5_V_read.read().is_01())? sc_lv<1>(): sc_lv<1>(tagReg_V_fu_298_p4.read() == tag_5_V_read.read());
}

void ReadHit::thread_tmp_26_6_fu_445_p2() {
    tmp_26_6_fu_445_p2 = (!tagReg_V_fu_298_p4.read().is_01() || !tag_6_V_read.read().is_01())? sc_lv<1>(): sc_lv<1>(tagReg_V_fu_298_p4.read() == tag_6_V_read.read());
}

void ReadHit::thread_tmp_26_7_fu_459_p2() {
    tmp_26_7_fu_459_p2 = (!tagReg_V_fu_298_p4.read().is_01() || !tag_7_V_read.read().is_01())? sc_lv<1>(): sc_lv<1>(tagReg_V_fu_298_p4.read() == tag_7_V_read.read());
}

void ReadHit::thread_tmp_2_fu_325_p2() {
    tmp_2_fu_325_p2 = (!tagReg_V_fu_298_p4.read().is_01() || !tag_0_V_read.read().is_01())? sc_lv<1>(): sc_lv<1>(tagReg_V_fu_298_p4.read() == tag_0_V_read.read());
}

void ReadHit::thread_tmp_54_fu_321_p1() {
    tmp_54_fu_321_p1 = valid_V.read().range(1-1, 0);
}

void ReadHit::thread_tmp_55_fu_337_p3() {
    tmp_55_fu_337_p3 = valid_V.read().range(1, 1);
}

void ReadHit::thread_tmp_56_fu_357_p3() {
    tmp_56_fu_357_p3 = valid_V.read().range(2, 2);
}

void ReadHit::thread_tmp_57_fu_377_p3() {
    tmp_57_fu_377_p3 = valid_V.read().range(3, 3);
}

void ReadHit::thread_tmp_58_fu_397_p3() {
    tmp_58_fu_397_p3 = valid_V.read().range(4, 4);
}

void ReadHit::thread_tmp_59_fu_417_p3() {
    tmp_59_fu_417_p3 = valid_V.read().range(5, 5);
}

void ReadHit::thread_tmp_60_fu_437_p3() {
    tmp_60_fu_437_p3 = valid_V.read().range(6, 6);
}

void ReadHit::thread_tmp_61_fu_451_p3() {
    tmp_61_fu_451_p3 = valid_V.read().range(7, 7);
}

void ReadHit::thread_tmp_fu_308_p1() {
    tmp_fu_308_p1 = esl_zext<64,8>(indexReg_V_fu_288_p4.read());
}

void ReadHit::thread_tmp_s_fu_678_p2() {
    tmp_s_fu_678_p2 = (!mruArray_V_6_q0.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(mruArray_V_6_q0.read() == ap_const_lv8_FF);
}

void ReadHit::thread_val_assign_1_fu_689_p2() {
    val_assign_1_fu_689_p2 = (!indexReg_V_reg_745.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<1>(): sc_lv<1>(indexReg_V_reg_745.read() == ap_const_lv8_1);
}

void ReadHit::thread_val_assign_2_fu_694_p2() {
    val_assign_2_fu_694_p2 = (!indexReg_V_reg_745.read().is_01() || !ap_const_lv8_2.is_01())? sc_lv<1>(): sc_lv<1>(indexReg_V_reg_745.read() == ap_const_lv8_2);
}

void ReadHit::thread_val_assign_3_fu_699_p2() {
    val_assign_3_fu_699_p2 = (!indexReg_V_reg_745.read().is_01() || !ap_const_lv8_3.is_01())? sc_lv<1>(): sc_lv<1>(indexReg_V_reg_745.read() == ap_const_lv8_3);
}

void ReadHit::thread_val_assign_4_fu_704_p2() {
    val_assign_4_fu_704_p2 = (!indexReg_V_reg_745.read().is_01() || !ap_const_lv8_4.is_01())? sc_lv<1>(): sc_lv<1>(indexReg_V_reg_745.read() == ap_const_lv8_4);
}

void ReadHit::thread_val_assign_5_fu_709_p2() {
    val_assign_5_fu_709_p2 = (!indexReg_V_reg_745.read().is_01() || !ap_const_lv8_5.is_01())? sc_lv<1>(): sc_lv<1>(indexReg_V_reg_745.read() == ap_const_lv8_5);
}

void ReadHit::thread_val_assign_6_fu_714_p2() {
    val_assign_6_fu_714_p2 = (!indexReg_V_reg_745.read().is_01() || !ap_const_lv8_6.is_01())? sc_lv<1>(): sc_lv<1>(indexReg_V_reg_745.read() == ap_const_lv8_6);
}

void ReadHit::thread_val_assign_7_fu_719_p2() {
    val_assign_7_fu_719_p2 = (!indexReg_V_reg_745.read().is_01() || !ap_const_lv8_7.is_01())? sc_lv<1>(): sc_lv<1>(indexReg_V_reg_745.read() == ap_const_lv8_7);
}

void ReadHit::thread_val_assign_fu_684_p2() {
    val_assign_fu_684_p2 = (!indexReg_V_reg_745.read().is_01() || !ap_const_lv8_0.is_01())? sc_lv<1>(): sc_lv<1>(indexReg_V_reg_745.read() == ap_const_lv8_0);
}

void ReadHit::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

