// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="PLRUCache,hls_ip_2018_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7k325tffg900-2,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.375000,HLS_SYN_LAT=8,HLS_SYN_TPT=none,HLS_SYN_MEM=90,HLS_SYN_DSP=0,HLS_SYN_FF=4738,HLS_SYN_LUT=3979,HLS_VERSION=2018_2}" *)

module PLRUCache (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_dram_AWVALID,
        m_axi_dram_AWREADY,
        m_axi_dram_AWADDR,
        m_axi_dram_AWID,
        m_axi_dram_AWLEN,
        m_axi_dram_AWSIZE,
        m_axi_dram_AWBURST,
        m_axi_dram_AWLOCK,
        m_axi_dram_AWCACHE,
        m_axi_dram_AWPROT,
        m_axi_dram_AWQOS,
        m_axi_dram_AWREGION,
        m_axi_dram_AWUSER,
        m_axi_dram_WVALID,
        m_axi_dram_WREADY,
        m_axi_dram_WDATA,
        m_axi_dram_WSTRB,
        m_axi_dram_WLAST,
        m_axi_dram_WID,
        m_axi_dram_WUSER,
        m_axi_dram_ARVALID,
        m_axi_dram_ARREADY,
        m_axi_dram_ARADDR,
        m_axi_dram_ARID,
        m_axi_dram_ARLEN,
        m_axi_dram_ARSIZE,
        m_axi_dram_ARBURST,
        m_axi_dram_ARLOCK,
        m_axi_dram_ARCACHE,
        m_axi_dram_ARPROT,
        m_axi_dram_ARQOS,
        m_axi_dram_ARREGION,
        m_axi_dram_ARUSER,
        m_axi_dram_RVALID,
        m_axi_dram_RREADY,
        m_axi_dram_RDATA,
        m_axi_dram_RLAST,
        m_axi_dram_RID,
        m_axi_dram_RUSER,
        m_axi_dram_RRESP,
        m_axi_dram_BVALID,
        m_axi_dram_BREADY,
        m_axi_dram_BRESP,
        m_axi_dram_BID,
        m_axi_dram_BUSER,
        i_addr_V,
        i_wdata_V,
        i_op,
        dram_V,
        ap_return
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;
parameter    C_M_AXI_DRAM_ID_WIDTH = 1;
parameter    C_M_AXI_DRAM_ADDR_WIDTH = 32;
parameter    C_M_AXI_DRAM_DATA_WIDTH = 512;
parameter    C_M_AXI_DRAM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_DRAM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_DRAM_WUSER_WIDTH = 1;
parameter    C_M_AXI_DRAM_RUSER_WIDTH = 1;
parameter    C_M_AXI_DRAM_BUSER_WIDTH = 1;
parameter    C_M_AXI_DRAM_USER_VALUE = 0;
parameter    C_M_AXI_DRAM_PROT_VALUE = 0;
parameter    C_M_AXI_DRAM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_M_AXI_DRAM_WSTRB_WIDTH = (512 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_dram_AWVALID;
input   m_axi_dram_AWREADY;
output  [C_M_AXI_DRAM_ADDR_WIDTH - 1:0] m_axi_dram_AWADDR;
output  [C_M_AXI_DRAM_ID_WIDTH - 1:0] m_axi_dram_AWID;
output  [7:0] m_axi_dram_AWLEN;
output  [2:0] m_axi_dram_AWSIZE;
output  [1:0] m_axi_dram_AWBURST;
output  [1:0] m_axi_dram_AWLOCK;
output  [3:0] m_axi_dram_AWCACHE;
output  [2:0] m_axi_dram_AWPROT;
output  [3:0] m_axi_dram_AWQOS;
output  [3:0] m_axi_dram_AWREGION;
output  [C_M_AXI_DRAM_AWUSER_WIDTH - 1:0] m_axi_dram_AWUSER;
output   m_axi_dram_WVALID;
input   m_axi_dram_WREADY;
output  [C_M_AXI_DRAM_DATA_WIDTH - 1:0] m_axi_dram_WDATA;
output  [C_M_AXI_DRAM_WSTRB_WIDTH - 1:0] m_axi_dram_WSTRB;
output   m_axi_dram_WLAST;
output  [C_M_AXI_DRAM_ID_WIDTH - 1:0] m_axi_dram_WID;
output  [C_M_AXI_DRAM_WUSER_WIDTH - 1:0] m_axi_dram_WUSER;
output   m_axi_dram_ARVALID;
input   m_axi_dram_ARREADY;
output  [C_M_AXI_DRAM_ADDR_WIDTH - 1:0] m_axi_dram_ARADDR;
output  [C_M_AXI_DRAM_ID_WIDTH - 1:0] m_axi_dram_ARID;
output  [7:0] m_axi_dram_ARLEN;
output  [2:0] m_axi_dram_ARSIZE;
output  [1:0] m_axi_dram_ARBURST;
output  [1:0] m_axi_dram_ARLOCK;
output  [3:0] m_axi_dram_ARCACHE;
output  [2:0] m_axi_dram_ARPROT;
output  [3:0] m_axi_dram_ARQOS;
output  [3:0] m_axi_dram_ARREGION;
output  [C_M_AXI_DRAM_ARUSER_WIDTH - 1:0] m_axi_dram_ARUSER;
input   m_axi_dram_RVALID;
output   m_axi_dram_RREADY;
input  [C_M_AXI_DRAM_DATA_WIDTH - 1:0] m_axi_dram_RDATA;
input   m_axi_dram_RLAST;
input  [C_M_AXI_DRAM_ID_WIDTH - 1:0] m_axi_dram_RID;
input  [C_M_AXI_DRAM_RUSER_WIDTH - 1:0] m_axi_dram_RUSER;
input  [1:0] m_axi_dram_RRESP;
input   m_axi_dram_BVALID;
output   m_axi_dram_BREADY;
input  [1:0] m_axi_dram_BRESP;
input  [C_M_AXI_DRAM_ID_WIDTH - 1:0] m_axi_dram_BID;
input  [C_M_AXI_DRAM_BUSER_WIDTH - 1:0] m_axi_dram_BUSER;
input  [31:0] i_addr_V;
input  [511:0] i_wdata_V;
input   i_op;
input  [31:0] dram_V;
output  [511:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [3:0] validArray_V_address0;
reg    validArray_V_ce0;
reg    validArray_V_we0;
reg   [3:0] validArray_V_d0;
wire   [3:0] validArray_V_q0;
reg   [3:0] tagArray_V_0_address0;
reg    tagArray_V_0_ce0;
reg    tagArray_V_0_we0;
reg   [27:0] tagArray_V_0_d0;
wire   [27:0] tagArray_V_0_q0;
reg   [3:0] tagArray_V_1_address0;
reg    tagArray_V_1_ce0;
reg    tagArray_V_1_we0;
reg   [27:0] tagArray_V_1_d0;
wire   [27:0] tagArray_V_1_q0;
reg   [3:0] tagArray_V_2_address0;
reg    tagArray_V_2_ce0;
reg    tagArray_V_2_we0;
reg   [27:0] tagArray_V_2_d0;
wire   [27:0] tagArray_V_2_q0;
reg   [3:0] tagArray_V_3_address0;
reg    tagArray_V_3_ce0;
reg    tagArray_V_3_we0;
reg   [27:0] tagArray_V_3_d0;
wire   [27:0] tagArray_V_3_q0;
reg   [3:0] dataArray_V_0_address0;
reg    dataArray_V_0_ce0;
reg    dataArray_V_0_we0;
reg   [511:0] dataArray_V_0_d0;
wire   [511:0] dataArray_V_0_q0;
reg   [3:0] dataArray_V_1_address0;
reg    dataArray_V_1_ce0;
reg    dataArray_V_1_we0;
reg   [511:0] dataArray_V_1_d0;
wire   [511:0] dataArray_V_1_q0;
reg   [3:0] dataArray_V_2_address0;
reg    dataArray_V_2_ce0;
reg    dataArray_V_2_we0;
reg   [511:0] dataArray_V_2_d0;
wire   [511:0] dataArray_V_2_q0;
reg   [3:0] dataArray_V_3_address0;
reg    dataArray_V_3_ce0;
reg    dataArray_V_3_we0;
reg   [511:0] dataArray_V_3_d0;
wire   [511:0] dataArray_V_3_q0;
reg   [3:0] mruArray_V_address0;
reg    mruArray_V_ce0;
reg    mruArray_V_we0;
reg   [3:0] mruArray_V_d0;
wire   [3:0] mruArray_V_q0;
reg    dram_AWVALID;
wire    dram_AWREADY;
reg   [31:0] dram_AWADDR;
reg   [0:0] dram_AWID;
reg   [31:0] dram_AWLEN;
reg   [2:0] dram_AWSIZE;
reg   [1:0] dram_AWBURST;
reg   [1:0] dram_AWLOCK;
reg   [3:0] dram_AWCACHE;
reg   [2:0] dram_AWPROT;
reg   [3:0] dram_AWQOS;
reg   [3:0] dram_AWREGION;
reg   [0:0] dram_AWUSER;
reg    dram_WVALID;
wire    dram_WREADY;
reg   [511:0] dram_WDATA;
reg   [63:0] dram_WSTRB;
reg    dram_WLAST;
reg   [0:0] dram_WID;
reg   [0:0] dram_WUSER;
reg    dram_ARVALID;
wire    dram_ARREADY;
wire    dram_RVALID;
reg    dram_RREADY;
wire   [511:0] dram_RDATA;
wire    dram_RLAST;
wire   [0:0] dram_RID;
wire   [0:0] dram_RUSER;
wire   [1:0] dram_RRESP;
wire    dram_BVALID;
reg    dram_BREADY;
wire   [1:0] dram_BRESP;
wire   [0:0] dram_BID;
wire   [0:0] dram_BUSER;
reg   [27:0] p_Result_2_fu_340_p4;
reg   [27:0] p_Result_2_reg_501;
wire   [0:0] i_op_read_read_fu_108_p2;
wire    ap_CS_fsm_state2;
reg   [25:0] dram_V1_reg_519;
reg   [3:0] validArray_V_load_reg_525;
reg   [27:0] tag_0_V_reg_533;
reg   [27:0] tag_1_V_reg_541;
reg   [27:0] tag_2_V_reg_549;
reg   [27:0] tag_3_V_reg_557;
wire   [0:0] brmerge_fu_450_p2;
reg   [0:0] brmerge_reg_565;
wire   [0:0] brmerge1_fu_462_p2;
reg   [0:0] brmerge1_reg_569;
wire   [511:0] grp_ReadHit_fu_269_ap_return;
wire    ap_CS_fsm_state3;
wire    grp_ReadHit_fu_269_ap_idle;
wire    grp_ReadHit_fu_269_ap_ready;
wire    grp_ReadHit_fu_269_ap_done;
wire    grp_ReadMiss_fu_201_ap_start;
wire    grp_ReadMiss_fu_201_ap_done;
wire    grp_ReadMiss_fu_201_ap_idle;
wire    grp_ReadMiss_fu_201_ap_ready;
wire    grp_ReadMiss_fu_201_m_axi_dram_V_AWVALID;
wire   [31:0] grp_ReadMiss_fu_201_m_axi_dram_V_AWADDR;
wire   [0:0] grp_ReadMiss_fu_201_m_axi_dram_V_AWID;
wire   [31:0] grp_ReadMiss_fu_201_m_axi_dram_V_AWLEN;
wire   [2:0] grp_ReadMiss_fu_201_m_axi_dram_V_AWSIZE;
wire   [1:0] grp_ReadMiss_fu_201_m_axi_dram_V_AWBURST;
wire   [1:0] grp_ReadMiss_fu_201_m_axi_dram_V_AWLOCK;
wire   [3:0] grp_ReadMiss_fu_201_m_axi_dram_V_AWCACHE;
wire   [2:0] grp_ReadMiss_fu_201_m_axi_dram_V_AWPROT;
wire   [3:0] grp_ReadMiss_fu_201_m_axi_dram_V_AWQOS;
wire   [3:0] grp_ReadMiss_fu_201_m_axi_dram_V_AWREGION;
wire   [0:0] grp_ReadMiss_fu_201_m_axi_dram_V_AWUSER;
wire    grp_ReadMiss_fu_201_m_axi_dram_V_WVALID;
wire   [511:0] grp_ReadMiss_fu_201_m_axi_dram_V_WDATA;
wire   [63:0] grp_ReadMiss_fu_201_m_axi_dram_V_WSTRB;
wire    grp_ReadMiss_fu_201_m_axi_dram_V_WLAST;
wire   [0:0] grp_ReadMiss_fu_201_m_axi_dram_V_WID;
wire   [0:0] grp_ReadMiss_fu_201_m_axi_dram_V_WUSER;
wire    grp_ReadMiss_fu_201_m_axi_dram_V_ARVALID;
wire   [31:0] grp_ReadMiss_fu_201_m_axi_dram_V_ARADDR;
wire   [0:0] grp_ReadMiss_fu_201_m_axi_dram_V_ARID;
wire   [31:0] grp_ReadMiss_fu_201_m_axi_dram_V_ARLEN;
wire   [2:0] grp_ReadMiss_fu_201_m_axi_dram_V_ARSIZE;
wire   [1:0] grp_ReadMiss_fu_201_m_axi_dram_V_ARBURST;
wire   [1:0] grp_ReadMiss_fu_201_m_axi_dram_V_ARLOCK;
wire   [3:0] grp_ReadMiss_fu_201_m_axi_dram_V_ARCACHE;
wire   [2:0] grp_ReadMiss_fu_201_m_axi_dram_V_ARPROT;
wire   [3:0] grp_ReadMiss_fu_201_m_axi_dram_V_ARQOS;
wire   [3:0] grp_ReadMiss_fu_201_m_axi_dram_V_ARREGION;
wire   [0:0] grp_ReadMiss_fu_201_m_axi_dram_V_ARUSER;
wire    grp_ReadMiss_fu_201_m_axi_dram_V_RREADY;
wire    grp_ReadMiss_fu_201_m_axi_dram_V_BREADY;
wire   [3:0] grp_ReadMiss_fu_201_validArray_V_4_address0;
wire    grp_ReadMiss_fu_201_validArray_V_4_ce0;
wire    grp_ReadMiss_fu_201_validArray_V_4_we0;
wire   [3:0] grp_ReadMiss_fu_201_validArray_V_4_d0;
wire   [3:0] grp_ReadMiss_fu_201_tagArray_0_V_address0;
wire    grp_ReadMiss_fu_201_tagArray_0_V_ce0;
wire    grp_ReadMiss_fu_201_tagArray_0_V_we0;
wire   [27:0] grp_ReadMiss_fu_201_tagArray_0_V_d0;
wire   [3:0] grp_ReadMiss_fu_201_tagArray_1_V_address0;
wire    grp_ReadMiss_fu_201_tagArray_1_V_ce0;
wire    grp_ReadMiss_fu_201_tagArray_1_V_we0;
wire   [27:0] grp_ReadMiss_fu_201_tagArray_1_V_d0;
wire   [3:0] grp_ReadMiss_fu_201_tagArray_2_V_address0;
wire    grp_ReadMiss_fu_201_tagArray_2_V_ce0;
wire    grp_ReadMiss_fu_201_tagArray_2_V_we0;
wire   [27:0] grp_ReadMiss_fu_201_tagArray_2_V_d0;
wire   [3:0] grp_ReadMiss_fu_201_tagArray_3_V_address0;
wire    grp_ReadMiss_fu_201_tagArray_3_V_ce0;
wire    grp_ReadMiss_fu_201_tagArray_3_V_we0;
wire   [27:0] grp_ReadMiss_fu_201_tagArray_3_V_d0;
wire   [3:0] grp_ReadMiss_fu_201_dataArray_0_V_address0;
wire    grp_ReadMiss_fu_201_dataArray_0_V_ce0;
wire    grp_ReadMiss_fu_201_dataArray_0_V_we0;
wire   [511:0] grp_ReadMiss_fu_201_dataArray_0_V_d0;
wire   [3:0] grp_ReadMiss_fu_201_dataArray_1_V_address0;
wire    grp_ReadMiss_fu_201_dataArray_1_V_ce0;
wire    grp_ReadMiss_fu_201_dataArray_1_V_we0;
wire   [511:0] grp_ReadMiss_fu_201_dataArray_1_V_d0;
wire   [3:0] grp_ReadMiss_fu_201_dataArray_2_V_address0;
wire    grp_ReadMiss_fu_201_dataArray_2_V_ce0;
wire    grp_ReadMiss_fu_201_dataArray_2_V_we0;
wire   [511:0] grp_ReadMiss_fu_201_dataArray_2_V_d0;
wire   [3:0] grp_ReadMiss_fu_201_dataArray_3_V_address0;
wire    grp_ReadMiss_fu_201_dataArray_3_V_ce0;
wire    grp_ReadMiss_fu_201_dataArray_3_V_we0;
wire   [511:0] grp_ReadMiss_fu_201_dataArray_3_V_d0;
wire   [3:0] grp_ReadMiss_fu_201_mruArray_V_4_address0;
wire    grp_ReadMiss_fu_201_mruArray_V_4_ce0;
wire    grp_ReadMiss_fu_201_mruArray_V_4_we0;
wire   [3:0] grp_ReadMiss_fu_201_mruArray_V_4_d0;
wire   [511:0] grp_ReadMiss_fu_201_ap_return;
wire    grp_WriteMiss_fu_235_ap_start;
wire    grp_WriteMiss_fu_235_ap_done;
wire    grp_WriteMiss_fu_235_ap_idle;
wire    grp_WriteMiss_fu_235_ap_ready;
wire    grp_WriteMiss_fu_235_m_axi_dram_V_AWVALID;
wire   [31:0] grp_WriteMiss_fu_235_m_axi_dram_V_AWADDR;
wire   [0:0] grp_WriteMiss_fu_235_m_axi_dram_V_AWID;
wire   [31:0] grp_WriteMiss_fu_235_m_axi_dram_V_AWLEN;
wire   [2:0] grp_WriteMiss_fu_235_m_axi_dram_V_AWSIZE;
wire   [1:0] grp_WriteMiss_fu_235_m_axi_dram_V_AWBURST;
wire   [1:0] grp_WriteMiss_fu_235_m_axi_dram_V_AWLOCK;
wire   [3:0] grp_WriteMiss_fu_235_m_axi_dram_V_AWCACHE;
wire   [2:0] grp_WriteMiss_fu_235_m_axi_dram_V_AWPROT;
wire   [3:0] grp_WriteMiss_fu_235_m_axi_dram_V_AWQOS;
wire   [3:0] grp_WriteMiss_fu_235_m_axi_dram_V_AWREGION;
wire   [0:0] grp_WriteMiss_fu_235_m_axi_dram_V_AWUSER;
wire    grp_WriteMiss_fu_235_m_axi_dram_V_WVALID;
wire   [511:0] grp_WriteMiss_fu_235_m_axi_dram_V_WDATA;
wire   [63:0] grp_WriteMiss_fu_235_m_axi_dram_V_WSTRB;
wire    grp_WriteMiss_fu_235_m_axi_dram_V_WLAST;
wire   [0:0] grp_WriteMiss_fu_235_m_axi_dram_V_WID;
wire   [0:0] grp_WriteMiss_fu_235_m_axi_dram_V_WUSER;
wire    grp_WriteMiss_fu_235_m_axi_dram_V_ARVALID;
wire   [31:0] grp_WriteMiss_fu_235_m_axi_dram_V_ARADDR;
wire   [0:0] grp_WriteMiss_fu_235_m_axi_dram_V_ARID;
wire   [31:0] grp_WriteMiss_fu_235_m_axi_dram_V_ARLEN;
wire   [2:0] grp_WriteMiss_fu_235_m_axi_dram_V_ARSIZE;
wire   [1:0] grp_WriteMiss_fu_235_m_axi_dram_V_ARBURST;
wire   [1:0] grp_WriteMiss_fu_235_m_axi_dram_V_ARLOCK;
wire   [3:0] grp_WriteMiss_fu_235_m_axi_dram_V_ARCACHE;
wire   [2:0] grp_WriteMiss_fu_235_m_axi_dram_V_ARPROT;
wire   [3:0] grp_WriteMiss_fu_235_m_axi_dram_V_ARQOS;
wire   [3:0] grp_WriteMiss_fu_235_m_axi_dram_V_ARREGION;
wire   [0:0] grp_WriteMiss_fu_235_m_axi_dram_V_ARUSER;
wire    grp_WriteMiss_fu_235_m_axi_dram_V_RREADY;
wire    grp_WriteMiss_fu_235_m_axi_dram_V_BREADY;
wire   [3:0] grp_WriteMiss_fu_235_validArray_V_2_address0;
wire    grp_WriteMiss_fu_235_validArray_V_2_ce0;
wire    grp_WriteMiss_fu_235_validArray_V_2_we0;
wire   [3:0] grp_WriteMiss_fu_235_validArray_V_2_d0;
wire   [3:0] grp_WriteMiss_fu_235_tagArray_0_V_address0;
wire    grp_WriteMiss_fu_235_tagArray_0_V_ce0;
wire    grp_WriteMiss_fu_235_tagArray_0_V_we0;
wire   [27:0] grp_WriteMiss_fu_235_tagArray_0_V_d0;
wire   [3:0] grp_WriteMiss_fu_235_tagArray_1_V_address0;
wire    grp_WriteMiss_fu_235_tagArray_1_V_ce0;
wire    grp_WriteMiss_fu_235_tagArray_1_V_we0;
wire   [27:0] grp_WriteMiss_fu_235_tagArray_1_V_d0;
wire   [3:0] grp_WriteMiss_fu_235_tagArray_2_V_address0;
wire    grp_WriteMiss_fu_235_tagArray_2_V_ce0;
wire    grp_WriteMiss_fu_235_tagArray_2_V_we0;
wire   [27:0] grp_WriteMiss_fu_235_tagArray_2_V_d0;
wire   [3:0] grp_WriteMiss_fu_235_tagArray_3_V_address0;
wire    grp_WriteMiss_fu_235_tagArray_3_V_ce0;
wire    grp_WriteMiss_fu_235_tagArray_3_V_we0;
wire   [27:0] grp_WriteMiss_fu_235_tagArray_3_V_d0;
wire   [3:0] grp_WriteMiss_fu_235_mruArray_V_address0;
wire    grp_WriteMiss_fu_235_mruArray_V_ce0;
wire    grp_WriteMiss_fu_235_mruArray_V_we0;
wire   [3:0] grp_WriteMiss_fu_235_mruArray_V_d0;
wire   [3:0] grp_WriteMiss_fu_235_dataArray_V_0_address0;
wire    grp_WriteMiss_fu_235_dataArray_V_0_ce0;
wire    grp_WriteMiss_fu_235_dataArray_V_0_we0;
wire   [511:0] grp_WriteMiss_fu_235_dataArray_V_0_d0;
wire   [3:0] grp_WriteMiss_fu_235_dataArray_V_1_address0;
wire    grp_WriteMiss_fu_235_dataArray_V_1_ce0;
wire    grp_WriteMiss_fu_235_dataArray_V_1_we0;
wire   [511:0] grp_WriteMiss_fu_235_dataArray_V_1_d0;
wire   [3:0] grp_WriteMiss_fu_235_dataArray_V_2_address0;
wire    grp_WriteMiss_fu_235_dataArray_V_2_ce0;
wire    grp_WriteMiss_fu_235_dataArray_V_2_we0;
wire   [511:0] grp_WriteMiss_fu_235_dataArray_V_2_d0;
wire   [3:0] grp_WriteMiss_fu_235_dataArray_V_3_address0;
wire    grp_WriteMiss_fu_235_dataArray_V_3_ce0;
wire    grp_WriteMiss_fu_235_dataArray_V_3_we0;
wire   [511:0] grp_WriteMiss_fu_235_dataArray_V_3_d0;
wire    grp_ReadHit_fu_269_ap_start;
wire   [3:0] grp_ReadHit_fu_269_dataArray_0_V_address0;
wire    grp_ReadHit_fu_269_dataArray_0_V_ce0;
wire   [3:0] grp_ReadHit_fu_269_dataArray_1_V_address0;
wire    grp_ReadHit_fu_269_dataArray_1_V_ce0;
wire   [3:0] grp_ReadHit_fu_269_dataArray_2_V_address0;
wire    grp_ReadHit_fu_269_dataArray_2_V_ce0;
wire   [3:0] grp_ReadHit_fu_269_dataArray_3_V_address0;
wire    grp_ReadHit_fu_269_dataArray_3_V_ce0;
wire   [3:0] grp_ReadHit_fu_269_mruArray_V_6_address0;
wire    grp_ReadHit_fu_269_mruArray_V_6_ce0;
wire    grp_ReadHit_fu_269_mruArray_V_6_we0;
wire   [3:0] grp_ReadHit_fu_269_mruArray_V_6_d0;
wire    grp_WriteHit_fu_294_ap_start;
wire    grp_WriteHit_fu_294_ap_done;
wire    grp_WriteHit_fu_294_ap_idle;
wire    grp_WriteHit_fu_294_ap_ready;
wire   [3:0] grp_WriteHit_fu_294_dataArray_0_V_address0;
wire    grp_WriteHit_fu_294_dataArray_0_V_ce0;
wire    grp_WriteHit_fu_294_dataArray_0_V_we0;
wire   [511:0] grp_WriteHit_fu_294_dataArray_0_V_d0;
wire   [3:0] grp_WriteHit_fu_294_dataArray_1_V_address0;
wire    grp_WriteHit_fu_294_dataArray_1_V_ce0;
wire    grp_WriteHit_fu_294_dataArray_1_V_we0;
wire   [511:0] grp_WriteHit_fu_294_dataArray_1_V_d0;
wire   [3:0] grp_WriteHit_fu_294_dataArray_2_V_address0;
wire    grp_WriteHit_fu_294_dataArray_2_V_ce0;
wire    grp_WriteHit_fu_294_dataArray_2_V_we0;
wire   [511:0] grp_WriteHit_fu_294_dataArray_2_V_d0;
wire   [3:0] grp_WriteHit_fu_294_dataArray_3_V_address0;
wire    grp_WriteHit_fu_294_dataArray_3_V_ce0;
wire    grp_WriteHit_fu_294_dataArray_3_V_we0;
wire   [511:0] grp_WriteHit_fu_294_dataArray_3_V_d0;
wire   [3:0] grp_WriteHit_fu_294_mruArray_V_2_address0;
wire    grp_WriteHit_fu_294_mruArray_V_2_ce0;
wire    grp_WriteHit_fu_294_mruArray_V_2_we0;
wire   [3:0] grp_WriteHit_fu_294_mruArray_V_2_d0;
reg   [511:0] ap_phi_mux_agg_result_V_2_phi_fu_189_p8;
reg   [511:0] agg_result_V_2_reg_185;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state6;
reg    ap_predicate_op65_call_state6;
reg    ap_predicate_op67_call_state6;
reg    ap_block_state6_on_subcall_done;
reg    grp_ReadMiss_fu_201_ap_start_reg;
wire    ap_CS_fsm_state5;
reg    grp_WriteMiss_fu_235_ap_start_reg;
wire    ap_CS_fsm_state7;
reg    grp_ReadHit_fu_269_ap_start_reg;
reg    grp_WriteHit_fu_294_ap_start_reg;
wire   [63:0] tmp_9_fu_331_p1;
reg   [3:0] p_Result_s_fu_321_p4;
wire   [0:0] tmp_fu_360_p1;
wire   [0:0] tmp_1_fu_364_p2;
wire   [0:0] tmp_42_fu_375_p3;
wire   [0:0] tmp_44_1_fu_383_p2;
wire   [0:0] tmp_43_fu_394_p3;
wire   [0:0] tmp_44_2_fu_402_p2;
wire   [0:0] tmp_44_fu_413_p3;
wire   [0:0] tmp_44_3_fu_421_p2;
wire   [0:0] tmp_45_3_fu_426_p2;
wire   [0:0] tmp_45_2_fu_407_p2;
wire   [0:0] tmp_45_1_fu_388_p2;
wire   [0:0] tmp_2_fu_369_p2;
wire   [3:0] p_Result_32_3_fu_432_p5;
wire   [0:0] tmp_s_fu_444_p2;
wire   [0:0] brmerge_fu_450_p1;
wire   [0:0] i_op_not_fu_456_p0;
wire   [0:0] i_op_not_fu_456_p2;
reg   [6:0] ap_NS_fsm;
reg    ap_condition_758;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 grp_ReadMiss_fu_201_ap_start_reg = 1'b0;
#0 grp_WriteMiss_fu_235_ap_start_reg = 1'b0;
#0 grp_ReadHit_fu_269_ap_start_reg = 1'b0;
#0 grp_WriteHit_fu_294_ap_start_reg = 1'b0;
end

PLRUCache_validArdEe #(
    .DataWidth( 4 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
validArray_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(validArray_V_address0),
    .ce0(validArray_V_ce0),
    .we0(validArray_V_we0),
    .d0(validArray_V_d0),
    .q0(validArray_V_q0)
);

PLRUCache_tagArraeOg #(
    .DataWidth( 28 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
tagArray_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(tagArray_V_0_address0),
    .ce0(tagArray_V_0_ce0),
    .we0(tagArray_V_0_we0),
    .d0(tagArray_V_0_d0),
    .q0(tagArray_V_0_q0)
);

PLRUCache_tagArraeOg #(
    .DataWidth( 28 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
tagArray_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(tagArray_V_1_address0),
    .ce0(tagArray_V_1_ce0),
    .we0(tagArray_V_1_we0),
    .d0(tagArray_V_1_d0),
    .q0(tagArray_V_1_q0)
);

PLRUCache_tagArraeOg #(
    .DataWidth( 28 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
tagArray_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(tagArray_V_2_address0),
    .ce0(tagArray_V_2_ce0),
    .we0(tagArray_V_2_we0),
    .d0(tagArray_V_2_d0),
    .q0(tagArray_V_2_q0)
);

PLRUCache_tagArraeOg #(
    .DataWidth( 28 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
tagArray_V_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(tagArray_V_3_address0),
    .ce0(tagArray_V_3_ce0),
    .we0(tagArray_V_3_we0),
    .d0(tagArray_V_3_d0),
    .q0(tagArray_V_3_q0)
);

PLRUCache_dataArribs #(
    .DataWidth( 512 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
dataArray_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(dataArray_V_0_address0),
    .ce0(dataArray_V_0_ce0),
    .we0(dataArray_V_0_we0),
    .d0(dataArray_V_0_d0),
    .q0(dataArray_V_0_q0)
);

PLRUCache_dataArribs #(
    .DataWidth( 512 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
dataArray_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(dataArray_V_1_address0),
    .ce0(dataArray_V_1_ce0),
    .we0(dataArray_V_1_we0),
    .d0(dataArray_V_1_d0),
    .q0(dataArray_V_1_q0)
);

PLRUCache_dataArribs #(
    .DataWidth( 512 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
dataArray_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(dataArray_V_2_address0),
    .ce0(dataArray_V_2_ce0),
    .we0(dataArray_V_2_we0),
    .d0(dataArray_V_2_d0),
    .q0(dataArray_V_2_q0)
);

PLRUCache_dataArribs #(
    .DataWidth( 512 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
dataArray_V_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(dataArray_V_3_address0),
    .ce0(dataArray_V_3_ce0),
    .we0(dataArray_V_3_we0),
    .d0(dataArray_V_3_d0),
    .q0(dataArray_V_3_q0)
);

PLRUCache_validArdEe #(
    .DataWidth( 4 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
mruArray_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(mruArray_V_address0),
    .ce0(mruArray_V_ce0),
    .we0(mruArray_V_we0),
    .d0(mruArray_V_d0),
    .q0(mruArray_V_q0)
);

PLRUCache_dram_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 512 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_DRAM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_DRAM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_DRAM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_DRAM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_DRAM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_DRAM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_DRAM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_DRAM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_DRAM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_DRAM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_DRAM_CACHE_VALUE ))
PLRUCache_dram_m_axi_U(
    .AWVALID(m_axi_dram_AWVALID),
    .AWREADY(m_axi_dram_AWREADY),
    .AWADDR(m_axi_dram_AWADDR),
    .AWID(m_axi_dram_AWID),
    .AWLEN(m_axi_dram_AWLEN),
    .AWSIZE(m_axi_dram_AWSIZE),
    .AWBURST(m_axi_dram_AWBURST),
    .AWLOCK(m_axi_dram_AWLOCK),
    .AWCACHE(m_axi_dram_AWCACHE),
    .AWPROT(m_axi_dram_AWPROT),
    .AWQOS(m_axi_dram_AWQOS),
    .AWREGION(m_axi_dram_AWREGION),
    .AWUSER(m_axi_dram_AWUSER),
    .WVALID(m_axi_dram_WVALID),
    .WREADY(m_axi_dram_WREADY),
    .WDATA(m_axi_dram_WDATA),
    .WSTRB(m_axi_dram_WSTRB),
    .WLAST(m_axi_dram_WLAST),
    .WID(m_axi_dram_WID),
    .WUSER(m_axi_dram_WUSER),
    .ARVALID(m_axi_dram_ARVALID),
    .ARREADY(m_axi_dram_ARREADY),
    .ARADDR(m_axi_dram_ARADDR),
    .ARID(m_axi_dram_ARID),
    .ARLEN(m_axi_dram_ARLEN),
    .ARSIZE(m_axi_dram_ARSIZE),
    .ARBURST(m_axi_dram_ARBURST),
    .ARLOCK(m_axi_dram_ARLOCK),
    .ARCACHE(m_axi_dram_ARCACHE),
    .ARPROT(m_axi_dram_ARPROT),
    .ARQOS(m_axi_dram_ARQOS),
    .ARREGION(m_axi_dram_ARREGION),
    .ARUSER(m_axi_dram_ARUSER),
    .RVALID(m_axi_dram_RVALID),
    .RREADY(m_axi_dram_RREADY),
    .RDATA(m_axi_dram_RDATA),
    .RLAST(m_axi_dram_RLAST),
    .RID(m_axi_dram_RID),
    .RUSER(m_axi_dram_RUSER),
    .RRESP(m_axi_dram_RRESP),
    .BVALID(m_axi_dram_BVALID),
    .BREADY(m_axi_dram_BREADY),
    .BRESP(m_axi_dram_BRESP),
    .BID(m_axi_dram_BID),
    .BUSER(m_axi_dram_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(dram_ARVALID),
    .I_ARREADY(dram_ARREADY),
    .I_ARADDR(grp_ReadMiss_fu_201_m_axi_dram_V_ARADDR),
    .I_ARID(grp_ReadMiss_fu_201_m_axi_dram_V_ARID),
    .I_ARLEN(grp_ReadMiss_fu_201_m_axi_dram_V_ARLEN),
    .I_ARSIZE(grp_ReadMiss_fu_201_m_axi_dram_V_ARSIZE),
    .I_ARLOCK(grp_ReadMiss_fu_201_m_axi_dram_V_ARLOCK),
    .I_ARCACHE(grp_ReadMiss_fu_201_m_axi_dram_V_ARCACHE),
    .I_ARQOS(grp_ReadMiss_fu_201_m_axi_dram_V_ARQOS),
    .I_ARPROT(grp_ReadMiss_fu_201_m_axi_dram_V_ARPROT),
    .I_ARUSER(grp_ReadMiss_fu_201_m_axi_dram_V_ARUSER),
    .I_ARBURST(grp_ReadMiss_fu_201_m_axi_dram_V_ARBURST),
    .I_ARREGION(grp_ReadMiss_fu_201_m_axi_dram_V_ARREGION),
    .I_RVALID(dram_RVALID),
    .I_RREADY(dram_RREADY),
    .I_RDATA(dram_RDATA),
    .I_RID(dram_RID),
    .I_RUSER(dram_RUSER),
    .I_RRESP(dram_RRESP),
    .I_RLAST(dram_RLAST),
    .I_AWVALID(dram_AWVALID),
    .I_AWREADY(dram_AWREADY),
    .I_AWADDR(dram_AWADDR),
    .I_AWID(dram_AWID),
    .I_AWLEN(dram_AWLEN),
    .I_AWSIZE(dram_AWSIZE),
    .I_AWLOCK(dram_AWLOCK),
    .I_AWCACHE(dram_AWCACHE),
    .I_AWQOS(dram_AWQOS),
    .I_AWPROT(dram_AWPROT),
    .I_AWUSER(dram_AWUSER),
    .I_AWBURST(dram_AWBURST),
    .I_AWREGION(dram_AWREGION),
    .I_WVALID(dram_WVALID),
    .I_WREADY(dram_WREADY),
    .I_WDATA(dram_WDATA),
    .I_WID(dram_WID),
    .I_WUSER(dram_WUSER),
    .I_WLAST(dram_WLAST),
    .I_WSTRB(dram_WSTRB),
    .I_BVALID(dram_BVALID),
    .I_BREADY(dram_BREADY),
    .I_BRESP(dram_BRESP),
    .I_BID(dram_BID),
    .I_BUSER(dram_BUSER)
);

ReadMiss grp_ReadMiss_fu_201(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_ReadMiss_fu_201_ap_start),
    .ap_done(grp_ReadMiss_fu_201_ap_done),
    .ap_idle(grp_ReadMiss_fu_201_ap_idle),
    .ap_ready(grp_ReadMiss_fu_201_ap_ready),
    .i_addr_V(i_addr_V),
    .m_axi_dram_V_AWVALID(grp_ReadMiss_fu_201_m_axi_dram_V_AWVALID),
    .m_axi_dram_V_AWREADY(dram_AWREADY),
    .m_axi_dram_V_AWADDR(grp_ReadMiss_fu_201_m_axi_dram_V_AWADDR),
    .m_axi_dram_V_AWID(grp_ReadMiss_fu_201_m_axi_dram_V_AWID),
    .m_axi_dram_V_AWLEN(grp_ReadMiss_fu_201_m_axi_dram_V_AWLEN),
    .m_axi_dram_V_AWSIZE(grp_ReadMiss_fu_201_m_axi_dram_V_AWSIZE),
    .m_axi_dram_V_AWBURST(grp_ReadMiss_fu_201_m_axi_dram_V_AWBURST),
    .m_axi_dram_V_AWLOCK(grp_ReadMiss_fu_201_m_axi_dram_V_AWLOCK),
    .m_axi_dram_V_AWCACHE(grp_ReadMiss_fu_201_m_axi_dram_V_AWCACHE),
    .m_axi_dram_V_AWPROT(grp_ReadMiss_fu_201_m_axi_dram_V_AWPROT),
    .m_axi_dram_V_AWQOS(grp_ReadMiss_fu_201_m_axi_dram_V_AWQOS),
    .m_axi_dram_V_AWREGION(grp_ReadMiss_fu_201_m_axi_dram_V_AWREGION),
    .m_axi_dram_V_AWUSER(grp_ReadMiss_fu_201_m_axi_dram_V_AWUSER),
    .m_axi_dram_V_WVALID(grp_ReadMiss_fu_201_m_axi_dram_V_WVALID),
    .m_axi_dram_V_WREADY(dram_WREADY),
    .m_axi_dram_V_WDATA(grp_ReadMiss_fu_201_m_axi_dram_V_WDATA),
    .m_axi_dram_V_WSTRB(grp_ReadMiss_fu_201_m_axi_dram_V_WSTRB),
    .m_axi_dram_V_WLAST(grp_ReadMiss_fu_201_m_axi_dram_V_WLAST),
    .m_axi_dram_V_WID(grp_ReadMiss_fu_201_m_axi_dram_V_WID),
    .m_axi_dram_V_WUSER(grp_ReadMiss_fu_201_m_axi_dram_V_WUSER),
    .m_axi_dram_V_ARVALID(grp_ReadMiss_fu_201_m_axi_dram_V_ARVALID),
    .m_axi_dram_V_ARREADY(dram_ARREADY),
    .m_axi_dram_V_ARADDR(grp_ReadMiss_fu_201_m_axi_dram_V_ARADDR),
    .m_axi_dram_V_ARID(grp_ReadMiss_fu_201_m_axi_dram_V_ARID),
    .m_axi_dram_V_ARLEN(grp_ReadMiss_fu_201_m_axi_dram_V_ARLEN),
    .m_axi_dram_V_ARSIZE(grp_ReadMiss_fu_201_m_axi_dram_V_ARSIZE),
    .m_axi_dram_V_ARBURST(grp_ReadMiss_fu_201_m_axi_dram_V_ARBURST),
    .m_axi_dram_V_ARLOCK(grp_ReadMiss_fu_201_m_axi_dram_V_ARLOCK),
    .m_axi_dram_V_ARCACHE(grp_ReadMiss_fu_201_m_axi_dram_V_ARCACHE),
    .m_axi_dram_V_ARPROT(grp_ReadMiss_fu_201_m_axi_dram_V_ARPROT),
    .m_axi_dram_V_ARQOS(grp_ReadMiss_fu_201_m_axi_dram_V_ARQOS),
    .m_axi_dram_V_ARREGION(grp_ReadMiss_fu_201_m_axi_dram_V_ARREGION),
    .m_axi_dram_V_ARUSER(grp_ReadMiss_fu_201_m_axi_dram_V_ARUSER),
    .m_axi_dram_V_RVALID(dram_RVALID),
    .m_axi_dram_V_RREADY(grp_ReadMiss_fu_201_m_axi_dram_V_RREADY),
    .m_axi_dram_V_RDATA(dram_RDATA),
    .m_axi_dram_V_RLAST(dram_RLAST),
    .m_axi_dram_V_RID(dram_RID),
    .m_axi_dram_V_RUSER(dram_RUSER),
    .m_axi_dram_V_RRESP(dram_RRESP),
    .m_axi_dram_V_BVALID(dram_BVALID),
    .m_axi_dram_V_BREADY(grp_ReadMiss_fu_201_m_axi_dram_V_BREADY),
    .m_axi_dram_V_BRESP(dram_BRESP),
    .m_axi_dram_V_BID(dram_BID),
    .m_axi_dram_V_BUSER(dram_BUSER),
    .dram_V_offset(dram_V1_reg_519),
    .valid_V(validArray_V_load_reg_525),
    .tag_0_V_read(tag_0_V_reg_533),
    .tag_1_V_read(tag_1_V_reg_541),
    .tag_2_V_read(tag_2_V_reg_549),
    .tag_3_V_read(tag_3_V_reg_557),
    .validArray_V_4_address0(grp_ReadMiss_fu_201_validArray_V_4_address0),
    .validArray_V_4_ce0(grp_ReadMiss_fu_201_validArray_V_4_ce0),
    .validArray_V_4_we0(grp_ReadMiss_fu_201_validArray_V_4_we0),
    .validArray_V_4_d0(grp_ReadMiss_fu_201_validArray_V_4_d0),
    .tagArray_0_V_address0(grp_ReadMiss_fu_201_tagArray_0_V_address0),
    .tagArray_0_V_ce0(grp_ReadMiss_fu_201_tagArray_0_V_ce0),
    .tagArray_0_V_we0(grp_ReadMiss_fu_201_tagArray_0_V_we0),
    .tagArray_0_V_d0(grp_ReadMiss_fu_201_tagArray_0_V_d0),
    .tagArray_1_V_address0(grp_ReadMiss_fu_201_tagArray_1_V_address0),
    .tagArray_1_V_ce0(grp_ReadMiss_fu_201_tagArray_1_V_ce0),
    .tagArray_1_V_we0(grp_ReadMiss_fu_201_tagArray_1_V_we0),
    .tagArray_1_V_d0(grp_ReadMiss_fu_201_tagArray_1_V_d0),
    .tagArray_2_V_address0(grp_ReadMiss_fu_201_tagArray_2_V_address0),
    .tagArray_2_V_ce0(grp_ReadMiss_fu_201_tagArray_2_V_ce0),
    .tagArray_2_V_we0(grp_ReadMiss_fu_201_tagArray_2_V_we0),
    .tagArray_2_V_d0(grp_ReadMiss_fu_201_tagArray_2_V_d0),
    .tagArray_3_V_address0(grp_ReadMiss_fu_201_tagArray_3_V_address0),
    .tagArray_3_V_ce0(grp_ReadMiss_fu_201_tagArray_3_V_ce0),
    .tagArray_3_V_we0(grp_ReadMiss_fu_201_tagArray_3_V_we0),
    .tagArray_3_V_d0(grp_ReadMiss_fu_201_tagArray_3_V_d0),
    .dataArray_0_V_address0(grp_ReadMiss_fu_201_dataArray_0_V_address0),
    .dataArray_0_V_ce0(grp_ReadMiss_fu_201_dataArray_0_V_ce0),
    .dataArray_0_V_we0(grp_ReadMiss_fu_201_dataArray_0_V_we0),
    .dataArray_0_V_d0(grp_ReadMiss_fu_201_dataArray_0_V_d0),
    .dataArray_0_V_q0(dataArray_V_0_q0),
    .dataArray_1_V_address0(grp_ReadMiss_fu_201_dataArray_1_V_address0),
    .dataArray_1_V_ce0(grp_ReadMiss_fu_201_dataArray_1_V_ce0),
    .dataArray_1_V_we0(grp_ReadMiss_fu_201_dataArray_1_V_we0),
    .dataArray_1_V_d0(grp_ReadMiss_fu_201_dataArray_1_V_d0),
    .dataArray_1_V_q0(dataArray_V_1_q0),
    .dataArray_2_V_address0(grp_ReadMiss_fu_201_dataArray_2_V_address0),
    .dataArray_2_V_ce0(grp_ReadMiss_fu_201_dataArray_2_V_ce0),
    .dataArray_2_V_we0(grp_ReadMiss_fu_201_dataArray_2_V_we0),
    .dataArray_2_V_d0(grp_ReadMiss_fu_201_dataArray_2_V_d0),
    .dataArray_2_V_q0(dataArray_V_2_q0),
    .dataArray_3_V_address0(grp_ReadMiss_fu_201_dataArray_3_V_address0),
    .dataArray_3_V_ce0(grp_ReadMiss_fu_201_dataArray_3_V_ce0),
    .dataArray_3_V_we0(grp_ReadMiss_fu_201_dataArray_3_V_we0),
    .dataArray_3_V_d0(grp_ReadMiss_fu_201_dataArray_3_V_d0),
    .dataArray_3_V_q0(dataArray_V_3_q0),
    .mruArray_V_4_address0(grp_ReadMiss_fu_201_mruArray_V_4_address0),
    .mruArray_V_4_ce0(grp_ReadMiss_fu_201_mruArray_V_4_ce0),
    .mruArray_V_4_we0(grp_ReadMiss_fu_201_mruArray_V_4_we0),
    .mruArray_V_4_d0(grp_ReadMiss_fu_201_mruArray_V_4_d0),
    .mruArray_V_4_q0(mruArray_V_q0),
    .ap_return(grp_ReadMiss_fu_201_ap_return)
);

WriteMiss grp_WriteMiss_fu_235(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_WriteMiss_fu_235_ap_start),
    .ap_done(grp_WriteMiss_fu_235_ap_done),
    .ap_idle(grp_WriteMiss_fu_235_ap_idle),
    .ap_ready(grp_WriteMiss_fu_235_ap_ready),
    .i_addr_V(i_addr_V),
    .i_wdata_V(i_wdata_V),
    .m_axi_dram_V_AWVALID(grp_WriteMiss_fu_235_m_axi_dram_V_AWVALID),
    .m_axi_dram_V_AWREADY(dram_AWREADY),
    .m_axi_dram_V_AWADDR(grp_WriteMiss_fu_235_m_axi_dram_V_AWADDR),
    .m_axi_dram_V_AWID(grp_WriteMiss_fu_235_m_axi_dram_V_AWID),
    .m_axi_dram_V_AWLEN(grp_WriteMiss_fu_235_m_axi_dram_V_AWLEN),
    .m_axi_dram_V_AWSIZE(grp_WriteMiss_fu_235_m_axi_dram_V_AWSIZE),
    .m_axi_dram_V_AWBURST(grp_WriteMiss_fu_235_m_axi_dram_V_AWBURST),
    .m_axi_dram_V_AWLOCK(grp_WriteMiss_fu_235_m_axi_dram_V_AWLOCK),
    .m_axi_dram_V_AWCACHE(grp_WriteMiss_fu_235_m_axi_dram_V_AWCACHE),
    .m_axi_dram_V_AWPROT(grp_WriteMiss_fu_235_m_axi_dram_V_AWPROT),
    .m_axi_dram_V_AWQOS(grp_WriteMiss_fu_235_m_axi_dram_V_AWQOS),
    .m_axi_dram_V_AWREGION(grp_WriteMiss_fu_235_m_axi_dram_V_AWREGION),
    .m_axi_dram_V_AWUSER(grp_WriteMiss_fu_235_m_axi_dram_V_AWUSER),
    .m_axi_dram_V_WVALID(grp_WriteMiss_fu_235_m_axi_dram_V_WVALID),
    .m_axi_dram_V_WREADY(dram_WREADY),
    .m_axi_dram_V_WDATA(grp_WriteMiss_fu_235_m_axi_dram_V_WDATA),
    .m_axi_dram_V_WSTRB(grp_WriteMiss_fu_235_m_axi_dram_V_WSTRB),
    .m_axi_dram_V_WLAST(grp_WriteMiss_fu_235_m_axi_dram_V_WLAST),
    .m_axi_dram_V_WID(grp_WriteMiss_fu_235_m_axi_dram_V_WID),
    .m_axi_dram_V_WUSER(grp_WriteMiss_fu_235_m_axi_dram_V_WUSER),
    .m_axi_dram_V_ARVALID(grp_WriteMiss_fu_235_m_axi_dram_V_ARVALID),
    .m_axi_dram_V_ARREADY(1'b0),
    .m_axi_dram_V_ARADDR(grp_WriteMiss_fu_235_m_axi_dram_V_ARADDR),
    .m_axi_dram_V_ARID(grp_WriteMiss_fu_235_m_axi_dram_V_ARID),
    .m_axi_dram_V_ARLEN(grp_WriteMiss_fu_235_m_axi_dram_V_ARLEN),
    .m_axi_dram_V_ARSIZE(grp_WriteMiss_fu_235_m_axi_dram_V_ARSIZE),
    .m_axi_dram_V_ARBURST(grp_WriteMiss_fu_235_m_axi_dram_V_ARBURST),
    .m_axi_dram_V_ARLOCK(grp_WriteMiss_fu_235_m_axi_dram_V_ARLOCK),
    .m_axi_dram_V_ARCACHE(grp_WriteMiss_fu_235_m_axi_dram_V_ARCACHE),
    .m_axi_dram_V_ARPROT(grp_WriteMiss_fu_235_m_axi_dram_V_ARPROT),
    .m_axi_dram_V_ARQOS(grp_WriteMiss_fu_235_m_axi_dram_V_ARQOS),
    .m_axi_dram_V_ARREGION(grp_WriteMiss_fu_235_m_axi_dram_V_ARREGION),
    .m_axi_dram_V_ARUSER(grp_WriteMiss_fu_235_m_axi_dram_V_ARUSER),
    .m_axi_dram_V_RVALID(1'b0),
    .m_axi_dram_V_RREADY(grp_WriteMiss_fu_235_m_axi_dram_V_RREADY),
    .m_axi_dram_V_RDATA(512'd0),
    .m_axi_dram_V_RLAST(1'b0),
    .m_axi_dram_V_RID(1'd0),
    .m_axi_dram_V_RUSER(1'd0),
    .m_axi_dram_V_RRESP(2'd0),
    .m_axi_dram_V_BVALID(dram_BVALID),
    .m_axi_dram_V_BREADY(grp_WriteMiss_fu_235_m_axi_dram_V_BREADY),
    .m_axi_dram_V_BRESP(dram_BRESP),
    .m_axi_dram_V_BID(dram_BID),
    .m_axi_dram_V_BUSER(dram_BUSER),
    .dram_V_offset(dram_V1_reg_519),
    .valid_V(validArray_V_load_reg_525),
    .tag_0_V_read(tag_0_V_reg_533),
    .tag_1_V_read(tag_1_V_reg_541),
    .tag_2_V_read(tag_2_V_reg_549),
    .tag_3_V_read(tag_3_V_reg_557),
    .validArray_V_2_address0(grp_WriteMiss_fu_235_validArray_V_2_address0),
    .validArray_V_2_ce0(grp_WriteMiss_fu_235_validArray_V_2_ce0),
    .validArray_V_2_we0(grp_WriteMiss_fu_235_validArray_V_2_we0),
    .validArray_V_2_d0(grp_WriteMiss_fu_235_validArray_V_2_d0),
    .tagArray_0_V_address0(grp_WriteMiss_fu_235_tagArray_0_V_address0),
    .tagArray_0_V_ce0(grp_WriteMiss_fu_235_tagArray_0_V_ce0),
    .tagArray_0_V_we0(grp_WriteMiss_fu_235_tagArray_0_V_we0),
    .tagArray_0_V_d0(grp_WriteMiss_fu_235_tagArray_0_V_d0),
    .tagArray_1_V_address0(grp_WriteMiss_fu_235_tagArray_1_V_address0),
    .tagArray_1_V_ce0(grp_WriteMiss_fu_235_tagArray_1_V_ce0),
    .tagArray_1_V_we0(grp_WriteMiss_fu_235_tagArray_1_V_we0),
    .tagArray_1_V_d0(grp_WriteMiss_fu_235_tagArray_1_V_d0),
    .tagArray_2_V_address0(grp_WriteMiss_fu_235_tagArray_2_V_address0),
    .tagArray_2_V_ce0(grp_WriteMiss_fu_235_tagArray_2_V_ce0),
    .tagArray_2_V_we0(grp_WriteMiss_fu_235_tagArray_2_V_we0),
    .tagArray_2_V_d0(grp_WriteMiss_fu_235_tagArray_2_V_d0),
    .tagArray_3_V_address0(grp_WriteMiss_fu_235_tagArray_3_V_address0),
    .tagArray_3_V_ce0(grp_WriteMiss_fu_235_tagArray_3_V_ce0),
    .tagArray_3_V_we0(grp_WriteMiss_fu_235_tagArray_3_V_we0),
    .tagArray_3_V_d0(grp_WriteMiss_fu_235_tagArray_3_V_d0),
    .mruArray_V_address0(grp_WriteMiss_fu_235_mruArray_V_address0),
    .mruArray_V_ce0(grp_WriteMiss_fu_235_mruArray_V_ce0),
    .mruArray_V_we0(grp_WriteMiss_fu_235_mruArray_V_we0),
    .mruArray_V_d0(grp_WriteMiss_fu_235_mruArray_V_d0),
    .mruArray_V_q0(mruArray_V_q0),
    .dataArray_V_0_address0(grp_WriteMiss_fu_235_dataArray_V_0_address0),
    .dataArray_V_0_ce0(grp_WriteMiss_fu_235_dataArray_V_0_ce0),
    .dataArray_V_0_we0(grp_WriteMiss_fu_235_dataArray_V_0_we0),
    .dataArray_V_0_d0(grp_WriteMiss_fu_235_dataArray_V_0_d0),
    .dataArray_V_0_q0(dataArray_V_0_q0),
    .dataArray_V_1_address0(grp_WriteMiss_fu_235_dataArray_V_1_address0),
    .dataArray_V_1_ce0(grp_WriteMiss_fu_235_dataArray_V_1_ce0),
    .dataArray_V_1_we0(grp_WriteMiss_fu_235_dataArray_V_1_we0),
    .dataArray_V_1_d0(grp_WriteMiss_fu_235_dataArray_V_1_d0),
    .dataArray_V_1_q0(dataArray_V_1_q0),
    .dataArray_V_2_address0(grp_WriteMiss_fu_235_dataArray_V_2_address0),
    .dataArray_V_2_ce0(grp_WriteMiss_fu_235_dataArray_V_2_ce0),
    .dataArray_V_2_we0(grp_WriteMiss_fu_235_dataArray_V_2_we0),
    .dataArray_V_2_d0(grp_WriteMiss_fu_235_dataArray_V_2_d0),
    .dataArray_V_2_q0(dataArray_V_2_q0),
    .dataArray_V_3_address0(grp_WriteMiss_fu_235_dataArray_V_3_address0),
    .dataArray_V_3_ce0(grp_WriteMiss_fu_235_dataArray_V_3_ce0),
    .dataArray_V_3_we0(grp_WriteMiss_fu_235_dataArray_V_3_we0),
    .dataArray_V_3_d0(grp_WriteMiss_fu_235_dataArray_V_3_d0),
    .dataArray_V_3_q0(dataArray_V_3_q0)
);

ReadHit grp_ReadHit_fu_269(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_ReadHit_fu_269_ap_start),
    .ap_done(grp_ReadHit_fu_269_ap_done),
    .ap_idle(grp_ReadHit_fu_269_ap_idle),
    .ap_ready(grp_ReadHit_fu_269_ap_ready),
    .i_addr_V(i_addr_V),
    .valid_V(validArray_V_load_reg_525),
    .tag_0_V_read(tag_0_V_reg_533),
    .tag_1_V_read(tag_1_V_reg_541),
    .tag_2_V_read(tag_2_V_reg_549),
    .tag_3_V_read(tag_3_V_reg_557),
    .dataArray_0_V_address0(grp_ReadHit_fu_269_dataArray_0_V_address0),
    .dataArray_0_V_ce0(grp_ReadHit_fu_269_dataArray_0_V_ce0),
    .dataArray_0_V_q0(dataArray_V_0_q0),
    .dataArray_1_V_address0(grp_ReadHit_fu_269_dataArray_1_V_address0),
    .dataArray_1_V_ce0(grp_ReadHit_fu_269_dataArray_1_V_ce0),
    .dataArray_1_V_q0(dataArray_V_1_q0),
    .dataArray_2_V_address0(grp_ReadHit_fu_269_dataArray_2_V_address0),
    .dataArray_2_V_ce0(grp_ReadHit_fu_269_dataArray_2_V_ce0),
    .dataArray_2_V_q0(dataArray_V_2_q0),
    .dataArray_3_V_address0(grp_ReadHit_fu_269_dataArray_3_V_address0),
    .dataArray_3_V_ce0(grp_ReadHit_fu_269_dataArray_3_V_ce0),
    .dataArray_3_V_q0(dataArray_V_3_q0),
    .mruArray_V_6_address0(grp_ReadHit_fu_269_mruArray_V_6_address0),
    .mruArray_V_6_ce0(grp_ReadHit_fu_269_mruArray_V_6_ce0),
    .mruArray_V_6_we0(grp_ReadHit_fu_269_mruArray_V_6_we0),
    .mruArray_V_6_d0(grp_ReadHit_fu_269_mruArray_V_6_d0),
    .mruArray_V_6_q0(mruArray_V_q0),
    .ap_return(grp_ReadHit_fu_269_ap_return)
);

WriteHit grp_WriteHit_fu_294(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_WriteHit_fu_294_ap_start),
    .ap_done(grp_WriteHit_fu_294_ap_done),
    .ap_idle(grp_WriteHit_fu_294_ap_idle),
    .ap_ready(grp_WriteHit_fu_294_ap_ready),
    .i_addr_V(i_addr_V),
    .i_wdata_V(i_wdata_V),
    .valid_V(validArray_V_load_reg_525),
    .tag_0_V_read(tag_0_V_reg_533),
    .tag_1_V_read(tag_1_V_reg_541),
    .tag_2_V_read(tag_2_V_reg_549),
    .tag_3_V_read(tag_3_V_reg_557),
    .dataArray_0_V_address0(grp_WriteHit_fu_294_dataArray_0_V_address0),
    .dataArray_0_V_ce0(grp_WriteHit_fu_294_dataArray_0_V_ce0),
    .dataArray_0_V_we0(grp_WriteHit_fu_294_dataArray_0_V_we0),
    .dataArray_0_V_d0(grp_WriteHit_fu_294_dataArray_0_V_d0),
    .dataArray_1_V_address0(grp_WriteHit_fu_294_dataArray_1_V_address0),
    .dataArray_1_V_ce0(grp_WriteHit_fu_294_dataArray_1_V_ce0),
    .dataArray_1_V_we0(grp_WriteHit_fu_294_dataArray_1_V_we0),
    .dataArray_1_V_d0(grp_WriteHit_fu_294_dataArray_1_V_d0),
    .dataArray_2_V_address0(grp_WriteHit_fu_294_dataArray_2_V_address0),
    .dataArray_2_V_ce0(grp_WriteHit_fu_294_dataArray_2_V_ce0),
    .dataArray_2_V_we0(grp_WriteHit_fu_294_dataArray_2_V_we0),
    .dataArray_2_V_d0(grp_WriteHit_fu_294_dataArray_2_V_d0),
    .dataArray_3_V_address0(grp_WriteHit_fu_294_dataArray_3_V_address0),
    .dataArray_3_V_ce0(grp_WriteHit_fu_294_dataArray_3_V_ce0),
    .dataArray_3_V_we0(grp_WriteHit_fu_294_dataArray_3_V_we0),
    .dataArray_3_V_d0(grp_WriteHit_fu_294_dataArray_3_V_d0),
    .mruArray_V_2_address0(grp_WriteHit_fu_294_mruArray_V_2_address0),
    .mruArray_V_2_ce0(grp_WriteHit_fu_294_mruArray_V_2_ce0),
    .mruArray_V_2_we0(grp_WriteHit_fu_294_mruArray_V_2_we0),
    .mruArray_V_2_d0(grp_WriteHit_fu_294_mruArray_V_2_d0),
    .mruArray_V_2_q0(mruArray_V_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_ReadHit_fu_269_ap_start_reg <= 1'b0;
    end else begin
        if (((brmerge_fu_450_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_ReadHit_fu_269_ap_start_reg <= 1'b1;
        end else if ((grp_ReadHit_fu_269_ap_ready == 1'b1)) begin
            grp_ReadHit_fu_269_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_ReadMiss_fu_201_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_ReadMiss_fu_201_ap_start_reg <= 1'b1;
        end else if ((grp_ReadMiss_fu_201_ap_ready == 1'b1)) begin
            grp_ReadMiss_fu_201_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_WriteHit_fu_294_ap_start_reg <= 1'b0;
    end else begin
        if (((brmerge1_fu_462_p2 == 1'd0) & (brmerge_fu_450_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_WriteHit_fu_294_ap_start_reg <= 1'b1;
        end else if ((grp_WriteHit_fu_294_ap_ready == 1'b1)) begin
            grp_WriteHit_fu_294_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_WriteMiss_fu_235_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_WriteMiss_fu_235_ap_start_reg <= 1'b1;
        end else if ((grp_WriteMiss_fu_235_ap_ready == 1'b1)) begin
            grp_WriteMiss_fu_235_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state6_on_subcall_done) & (brmerge1_reg_569 == 1'd1) & (brmerge_reg_565 == 1'd1) & (i_op_read_read_fu_108_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        agg_result_V_2_reg_185 <= grp_ReadMiss_fu_201_ap_return;
    end else if ((((1'b0 == ap_block_state6_on_subcall_done) & (brmerge1_reg_569 == 1'd1) & (brmerge_reg_565 == 1'd1) & (i_op_read_read_fu_108_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6)) | ((grp_WriteHit_fu_294_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4)))) begin
        agg_result_V_2_reg_185 <= 512'd0;
    end else if (((grp_ReadHit_fu_269_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        agg_result_V_2_reg_185 <= grp_ReadHit_fu_269_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((brmerge_fu_450_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        brmerge1_reg_569 <= brmerge1_fu_462_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        brmerge_reg_565 <= brmerge_fu_450_p2;
        dram_V1_reg_519 <= {{dram_V[31:6]}};
        tag_0_V_reg_533 <= tagArray_V_0_q0;
        tag_1_V_reg_541 <= tagArray_V_1_q0;
        tag_2_V_reg_549 <= tagArray_V_2_q0;
        tag_3_V_reg_557 <= tagArray_V_3_q0;
        validArray_V_load_reg_525 <= validArray_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        p_Result_2_reg_501 <= p_Result_2_fu_340_p4;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state6_on_subcall_done) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_758)) begin
        if ((i_op_read_read_fu_108_p2 == 1'd0)) begin
            ap_phi_mux_agg_result_V_2_phi_fu_189_p8 = grp_ReadMiss_fu_201_ap_return;
        end else if ((i_op_read_read_fu_108_p2 == 1'd1)) begin
            ap_phi_mux_agg_result_V_2_phi_fu_189_p8 = 512'd0;
        end else begin
            ap_phi_mux_agg_result_V_2_phi_fu_189_p8 = agg_result_V_2_reg_185;
        end
    end else begin
        ap_phi_mux_agg_result_V_2_phi_fu_189_p8 = agg_result_V_2_reg_185;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state6_on_subcall_done) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        dataArray_V_0_address0 = grp_WriteHit_fu_294_dataArray_0_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        dataArray_V_0_address0 = grp_ReadHit_fu_269_dataArray_0_V_address0;
    end else if (((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_0_address0 = grp_WriteMiss_fu_235_dataArray_V_0_address0;
    end else if (((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_0_address0 = grp_ReadMiss_fu_201_dataArray_0_V_address0;
    end else begin
        dataArray_V_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        dataArray_V_0_ce0 = grp_WriteHit_fu_294_dataArray_0_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        dataArray_V_0_ce0 = grp_ReadHit_fu_269_dataArray_0_V_ce0;
    end else if (((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_0_ce0 = grp_WriteMiss_fu_235_dataArray_V_0_ce0;
    end else if (((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_0_ce0 = grp_ReadMiss_fu_201_dataArray_0_V_ce0;
    end else begin
        dataArray_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        dataArray_V_0_d0 = grp_WriteHit_fu_294_dataArray_0_V_d0;
    end else if (((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_0_d0 = grp_WriteMiss_fu_235_dataArray_V_0_d0;
    end else if (((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_0_d0 = grp_ReadMiss_fu_201_dataArray_0_V_d0;
    end else begin
        dataArray_V_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        dataArray_V_0_we0 = grp_WriteHit_fu_294_dataArray_0_V_we0;
    end else if (((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_0_we0 = grp_WriteMiss_fu_235_dataArray_V_0_we0;
    end else if (((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_0_we0 = grp_ReadMiss_fu_201_dataArray_0_V_we0;
    end else begin
        dataArray_V_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        dataArray_V_1_address0 = grp_WriteHit_fu_294_dataArray_1_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        dataArray_V_1_address0 = grp_ReadHit_fu_269_dataArray_1_V_address0;
    end else if (((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_1_address0 = grp_WriteMiss_fu_235_dataArray_V_1_address0;
    end else if (((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_1_address0 = grp_ReadMiss_fu_201_dataArray_1_V_address0;
    end else begin
        dataArray_V_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        dataArray_V_1_ce0 = grp_WriteHit_fu_294_dataArray_1_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        dataArray_V_1_ce0 = grp_ReadHit_fu_269_dataArray_1_V_ce0;
    end else if (((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_1_ce0 = grp_WriteMiss_fu_235_dataArray_V_1_ce0;
    end else if (((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_1_ce0 = grp_ReadMiss_fu_201_dataArray_1_V_ce0;
    end else begin
        dataArray_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        dataArray_V_1_d0 = grp_WriteHit_fu_294_dataArray_1_V_d0;
    end else if (((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_1_d0 = grp_WriteMiss_fu_235_dataArray_V_1_d0;
    end else if (((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_1_d0 = grp_ReadMiss_fu_201_dataArray_1_V_d0;
    end else begin
        dataArray_V_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        dataArray_V_1_we0 = grp_WriteHit_fu_294_dataArray_1_V_we0;
    end else if (((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_1_we0 = grp_WriteMiss_fu_235_dataArray_V_1_we0;
    end else if (((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_1_we0 = grp_ReadMiss_fu_201_dataArray_1_V_we0;
    end else begin
        dataArray_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        dataArray_V_2_address0 = grp_WriteHit_fu_294_dataArray_2_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        dataArray_V_2_address0 = grp_ReadHit_fu_269_dataArray_2_V_address0;
    end else if (((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_2_address0 = grp_WriteMiss_fu_235_dataArray_V_2_address0;
    end else if (((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_2_address0 = grp_ReadMiss_fu_201_dataArray_2_V_address0;
    end else begin
        dataArray_V_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        dataArray_V_2_ce0 = grp_WriteHit_fu_294_dataArray_2_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        dataArray_V_2_ce0 = grp_ReadHit_fu_269_dataArray_2_V_ce0;
    end else if (((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_2_ce0 = grp_WriteMiss_fu_235_dataArray_V_2_ce0;
    end else if (((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_2_ce0 = grp_ReadMiss_fu_201_dataArray_2_V_ce0;
    end else begin
        dataArray_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        dataArray_V_2_d0 = grp_WriteHit_fu_294_dataArray_2_V_d0;
    end else if (((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_2_d0 = grp_WriteMiss_fu_235_dataArray_V_2_d0;
    end else if (((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_2_d0 = grp_ReadMiss_fu_201_dataArray_2_V_d0;
    end else begin
        dataArray_V_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        dataArray_V_2_we0 = grp_WriteHit_fu_294_dataArray_2_V_we0;
    end else if (((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_2_we0 = grp_WriteMiss_fu_235_dataArray_V_2_we0;
    end else if (((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_2_we0 = grp_ReadMiss_fu_201_dataArray_2_V_we0;
    end else begin
        dataArray_V_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        dataArray_V_3_address0 = grp_WriteHit_fu_294_dataArray_3_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        dataArray_V_3_address0 = grp_ReadHit_fu_269_dataArray_3_V_address0;
    end else if (((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_3_address0 = grp_WriteMiss_fu_235_dataArray_V_3_address0;
    end else if (((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_3_address0 = grp_ReadMiss_fu_201_dataArray_3_V_address0;
    end else begin
        dataArray_V_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        dataArray_V_3_ce0 = grp_WriteHit_fu_294_dataArray_3_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        dataArray_V_3_ce0 = grp_ReadHit_fu_269_dataArray_3_V_ce0;
    end else if (((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_3_ce0 = grp_WriteMiss_fu_235_dataArray_V_3_ce0;
    end else if (((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_3_ce0 = grp_ReadMiss_fu_201_dataArray_3_V_ce0;
    end else begin
        dataArray_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        dataArray_V_3_d0 = grp_WriteHit_fu_294_dataArray_3_V_d0;
    end else if (((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_3_d0 = grp_WriteMiss_fu_235_dataArray_V_3_d0;
    end else if (((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_3_d0 = grp_ReadMiss_fu_201_dataArray_3_V_d0;
    end else begin
        dataArray_V_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        dataArray_V_3_we0 = grp_WriteHit_fu_294_dataArray_3_V_we0;
    end else if (((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_3_we0 = grp_WriteMiss_fu_235_dataArray_V_3_we0;
    end else if (((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        dataArray_V_3_we0 = grp_ReadMiss_fu_201_dataArray_3_V_we0;
    end else begin
        dataArray_V_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_ARVALID = grp_ReadMiss_fu_201_m_axi_dram_V_ARVALID;
    end else begin
        dram_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_AWADDR = grp_WriteMiss_fu_235_m_axi_dram_V_AWADDR;
    end else if (((1'b1 == ap_CS_fsm_state5) | ((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_AWADDR = grp_ReadMiss_fu_201_m_axi_dram_V_AWADDR;
    end else begin
        dram_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_AWBURST = grp_WriteMiss_fu_235_m_axi_dram_V_AWBURST;
    end else if (((1'b1 == ap_CS_fsm_state5) | ((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_AWBURST = grp_ReadMiss_fu_201_m_axi_dram_V_AWBURST;
    end else begin
        dram_AWBURST = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_AWCACHE = grp_WriteMiss_fu_235_m_axi_dram_V_AWCACHE;
    end else if (((1'b1 == ap_CS_fsm_state5) | ((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_AWCACHE = grp_ReadMiss_fu_201_m_axi_dram_V_AWCACHE;
    end else begin
        dram_AWCACHE = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_AWID = grp_WriteMiss_fu_235_m_axi_dram_V_AWID;
    end else if (((1'b1 == ap_CS_fsm_state5) | ((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_AWID = grp_ReadMiss_fu_201_m_axi_dram_V_AWID;
    end else begin
        dram_AWID = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_AWLEN = grp_WriteMiss_fu_235_m_axi_dram_V_AWLEN;
    end else if (((1'b1 == ap_CS_fsm_state5) | ((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_AWLEN = grp_ReadMiss_fu_201_m_axi_dram_V_AWLEN;
    end else begin
        dram_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_AWLOCK = grp_WriteMiss_fu_235_m_axi_dram_V_AWLOCK;
    end else if (((1'b1 == ap_CS_fsm_state5) | ((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_AWLOCK = grp_ReadMiss_fu_201_m_axi_dram_V_AWLOCK;
    end else begin
        dram_AWLOCK = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_AWPROT = grp_WriteMiss_fu_235_m_axi_dram_V_AWPROT;
    end else if (((1'b1 == ap_CS_fsm_state5) | ((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_AWPROT = grp_ReadMiss_fu_201_m_axi_dram_V_AWPROT;
    end else begin
        dram_AWPROT = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_AWQOS = grp_WriteMiss_fu_235_m_axi_dram_V_AWQOS;
    end else if (((1'b1 == ap_CS_fsm_state5) | ((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_AWQOS = grp_ReadMiss_fu_201_m_axi_dram_V_AWQOS;
    end else begin
        dram_AWQOS = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_AWREGION = grp_WriteMiss_fu_235_m_axi_dram_V_AWREGION;
    end else if (((1'b1 == ap_CS_fsm_state5) | ((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_AWREGION = grp_ReadMiss_fu_201_m_axi_dram_V_AWREGION;
    end else begin
        dram_AWREGION = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_AWSIZE = grp_WriteMiss_fu_235_m_axi_dram_V_AWSIZE;
    end else if (((1'b1 == ap_CS_fsm_state5) | ((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_AWSIZE = grp_ReadMiss_fu_201_m_axi_dram_V_AWSIZE;
    end else begin
        dram_AWSIZE = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_AWUSER = grp_WriteMiss_fu_235_m_axi_dram_V_AWUSER;
    end else if (((1'b1 == ap_CS_fsm_state5) | ((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_AWUSER = grp_ReadMiss_fu_201_m_axi_dram_V_AWUSER;
    end else begin
        dram_AWUSER = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_AWVALID = grp_WriteMiss_fu_235_m_axi_dram_V_AWVALID;
    end else if (((1'b1 == ap_CS_fsm_state5) | ((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_AWVALID = grp_ReadMiss_fu_201_m_axi_dram_V_AWVALID;
    end else begin
        dram_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_BREADY = grp_WriteMiss_fu_235_m_axi_dram_V_BREADY;
    end else if (((1'b1 == ap_CS_fsm_state5) | ((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_BREADY = grp_ReadMiss_fu_201_m_axi_dram_V_BREADY;
    end else begin
        dram_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_RREADY = grp_ReadMiss_fu_201_m_axi_dram_V_RREADY;
    end else begin
        dram_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_WDATA = grp_WriteMiss_fu_235_m_axi_dram_V_WDATA;
    end else if (((1'b1 == ap_CS_fsm_state5) | ((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_WDATA = grp_ReadMiss_fu_201_m_axi_dram_V_WDATA;
    end else begin
        dram_WDATA = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_WID = grp_WriteMiss_fu_235_m_axi_dram_V_WID;
    end else if (((1'b1 == ap_CS_fsm_state5) | ((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_WID = grp_ReadMiss_fu_201_m_axi_dram_V_WID;
    end else begin
        dram_WID = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_WLAST = grp_WriteMiss_fu_235_m_axi_dram_V_WLAST;
    end else if (((1'b1 == ap_CS_fsm_state5) | ((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_WLAST = grp_ReadMiss_fu_201_m_axi_dram_V_WLAST;
    end else begin
        dram_WLAST = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_WSTRB = grp_WriteMiss_fu_235_m_axi_dram_V_WSTRB;
    end else if (((1'b1 == ap_CS_fsm_state5) | ((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_WSTRB = grp_ReadMiss_fu_201_m_axi_dram_V_WSTRB;
    end else begin
        dram_WSTRB = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_WUSER = grp_WriteMiss_fu_235_m_axi_dram_V_WUSER;
    end else if (((1'b1 == ap_CS_fsm_state5) | ((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_WUSER = grp_ReadMiss_fu_201_m_axi_dram_V_WUSER;
    end else begin
        dram_WUSER = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_WVALID = grp_WriteMiss_fu_235_m_axi_dram_V_WVALID;
    end else if (((1'b1 == ap_CS_fsm_state5) | ((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        dram_WVALID = grp_ReadMiss_fu_201_m_axi_dram_V_WVALID;
    end else begin
        dram_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        mruArray_V_address0 = grp_WriteHit_fu_294_mruArray_V_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        mruArray_V_address0 = grp_ReadHit_fu_269_mruArray_V_6_address0;
    end else if (((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        mruArray_V_address0 = grp_WriteMiss_fu_235_mruArray_V_address0;
    end else if (((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        mruArray_V_address0 = grp_ReadMiss_fu_201_mruArray_V_4_address0;
    end else begin
        mruArray_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        mruArray_V_ce0 = grp_WriteHit_fu_294_mruArray_V_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        mruArray_V_ce0 = grp_ReadHit_fu_269_mruArray_V_6_ce0;
    end else if (((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        mruArray_V_ce0 = grp_WriteMiss_fu_235_mruArray_V_ce0;
    end else if (((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        mruArray_V_ce0 = grp_ReadMiss_fu_201_mruArray_V_4_ce0;
    end else begin
        mruArray_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        mruArray_V_d0 = grp_WriteHit_fu_294_mruArray_V_2_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        mruArray_V_d0 = grp_ReadHit_fu_269_mruArray_V_6_d0;
    end else if (((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        mruArray_V_d0 = grp_WriteMiss_fu_235_mruArray_V_d0;
    end else if (((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        mruArray_V_d0 = grp_ReadMiss_fu_201_mruArray_V_4_d0;
    end else begin
        mruArray_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        mruArray_V_we0 = grp_WriteHit_fu_294_mruArray_V_2_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        mruArray_V_we0 = grp_ReadHit_fu_269_mruArray_V_6_we0;
    end else if (((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        mruArray_V_we0 = grp_WriteMiss_fu_235_mruArray_V_we0;
    end else if (((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        mruArray_V_we0 = grp_ReadMiss_fu_201_mruArray_V_4_we0;
    end else begin
        mruArray_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        tagArray_V_0_address0 = tmp_9_fu_331_p1;
    end else if (((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        tagArray_V_0_address0 = grp_WriteMiss_fu_235_tagArray_0_V_address0;
    end else if (((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        tagArray_V_0_address0 = grp_ReadMiss_fu_201_tagArray_0_V_address0;
    end else begin
        tagArray_V_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tagArray_V_0_ce0 = 1'b1;
    end else if (((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        tagArray_V_0_ce0 = grp_WriteMiss_fu_235_tagArray_0_V_ce0;
    end else if (((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        tagArray_V_0_ce0 = grp_ReadMiss_fu_201_tagArray_0_V_ce0;
    end else begin
        tagArray_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        if ((ap_predicate_op67_call_state6 == 1'b1)) begin
            tagArray_V_0_d0 = grp_WriteMiss_fu_235_tagArray_0_V_d0;
        end else if ((ap_predicate_op65_call_state6 == 1'b1)) begin
            tagArray_V_0_d0 = grp_ReadMiss_fu_201_tagArray_0_V_d0;
        end else begin
            tagArray_V_0_d0 = 'bx;
        end
    end else begin
        tagArray_V_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        if ((ap_predicate_op67_call_state6 == 1'b1)) begin
            tagArray_V_0_we0 = grp_WriteMiss_fu_235_tagArray_0_V_we0;
        end else if ((ap_predicate_op65_call_state6 == 1'b1)) begin
            tagArray_V_0_we0 = grp_ReadMiss_fu_201_tagArray_0_V_we0;
        end else begin
            tagArray_V_0_we0 = 1'b0;
        end
    end else begin
        tagArray_V_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        tagArray_V_1_address0 = tmp_9_fu_331_p1;
    end else if (((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        tagArray_V_1_address0 = grp_WriteMiss_fu_235_tagArray_1_V_address0;
    end else if (((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        tagArray_V_1_address0 = grp_ReadMiss_fu_201_tagArray_1_V_address0;
    end else begin
        tagArray_V_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tagArray_V_1_ce0 = 1'b1;
    end else if (((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        tagArray_V_1_ce0 = grp_WriteMiss_fu_235_tagArray_1_V_ce0;
    end else if (((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        tagArray_V_1_ce0 = grp_ReadMiss_fu_201_tagArray_1_V_ce0;
    end else begin
        tagArray_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        if ((ap_predicate_op67_call_state6 == 1'b1)) begin
            tagArray_V_1_d0 = grp_WriteMiss_fu_235_tagArray_1_V_d0;
        end else if ((ap_predicate_op65_call_state6 == 1'b1)) begin
            tagArray_V_1_d0 = grp_ReadMiss_fu_201_tagArray_1_V_d0;
        end else begin
            tagArray_V_1_d0 = 'bx;
        end
    end else begin
        tagArray_V_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        if ((ap_predicate_op67_call_state6 == 1'b1)) begin
            tagArray_V_1_we0 = grp_WriteMiss_fu_235_tagArray_1_V_we0;
        end else if ((ap_predicate_op65_call_state6 == 1'b1)) begin
            tagArray_V_1_we0 = grp_ReadMiss_fu_201_tagArray_1_V_we0;
        end else begin
            tagArray_V_1_we0 = 1'b0;
        end
    end else begin
        tagArray_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        tagArray_V_2_address0 = tmp_9_fu_331_p1;
    end else if (((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        tagArray_V_2_address0 = grp_WriteMiss_fu_235_tagArray_2_V_address0;
    end else if (((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        tagArray_V_2_address0 = grp_ReadMiss_fu_201_tagArray_2_V_address0;
    end else begin
        tagArray_V_2_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tagArray_V_2_ce0 = 1'b1;
    end else if (((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        tagArray_V_2_ce0 = grp_WriteMiss_fu_235_tagArray_2_V_ce0;
    end else if (((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        tagArray_V_2_ce0 = grp_ReadMiss_fu_201_tagArray_2_V_ce0;
    end else begin
        tagArray_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        if ((ap_predicate_op67_call_state6 == 1'b1)) begin
            tagArray_V_2_d0 = grp_WriteMiss_fu_235_tagArray_2_V_d0;
        end else if ((ap_predicate_op65_call_state6 == 1'b1)) begin
            tagArray_V_2_d0 = grp_ReadMiss_fu_201_tagArray_2_V_d0;
        end else begin
            tagArray_V_2_d0 = 'bx;
        end
    end else begin
        tagArray_V_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        if ((ap_predicate_op67_call_state6 == 1'b1)) begin
            tagArray_V_2_we0 = grp_WriteMiss_fu_235_tagArray_2_V_we0;
        end else if ((ap_predicate_op65_call_state6 == 1'b1)) begin
            tagArray_V_2_we0 = grp_ReadMiss_fu_201_tagArray_2_V_we0;
        end else begin
            tagArray_V_2_we0 = 1'b0;
        end
    end else begin
        tagArray_V_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        tagArray_V_3_address0 = tmp_9_fu_331_p1;
    end else if (((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        tagArray_V_3_address0 = grp_WriteMiss_fu_235_tagArray_3_V_address0;
    end else if (((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        tagArray_V_3_address0 = grp_ReadMiss_fu_201_tagArray_3_V_address0;
    end else begin
        tagArray_V_3_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tagArray_V_3_ce0 = 1'b1;
    end else if (((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        tagArray_V_3_ce0 = grp_WriteMiss_fu_235_tagArray_3_V_ce0;
    end else if (((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        tagArray_V_3_ce0 = grp_ReadMiss_fu_201_tagArray_3_V_ce0;
    end else begin
        tagArray_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        if ((ap_predicate_op67_call_state6 == 1'b1)) begin
            tagArray_V_3_d0 = grp_WriteMiss_fu_235_tagArray_3_V_d0;
        end else if ((ap_predicate_op65_call_state6 == 1'b1)) begin
            tagArray_V_3_d0 = grp_ReadMiss_fu_201_tagArray_3_V_d0;
        end else begin
            tagArray_V_3_d0 = 'bx;
        end
    end else begin
        tagArray_V_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        if ((ap_predicate_op67_call_state6 == 1'b1)) begin
            tagArray_V_3_we0 = grp_WriteMiss_fu_235_tagArray_3_V_we0;
        end else if ((ap_predicate_op65_call_state6 == 1'b1)) begin
            tagArray_V_3_we0 = grp_ReadMiss_fu_201_tagArray_3_V_we0;
        end else begin
            tagArray_V_3_we0 = 1'b0;
        end
    end else begin
        tagArray_V_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        validArray_V_address0 = tmp_9_fu_331_p1;
    end else if (((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        validArray_V_address0 = grp_WriteMiss_fu_235_validArray_V_2_address0;
    end else if (((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        validArray_V_address0 = grp_ReadMiss_fu_201_validArray_V_4_address0;
    end else begin
        validArray_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        validArray_V_ce0 = 1'b1;
    end else if (((ap_predicate_op67_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        validArray_V_ce0 = grp_WriteMiss_fu_235_validArray_V_2_ce0;
    end else if (((ap_predicate_op65_call_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        validArray_V_ce0 = grp_ReadMiss_fu_201_validArray_V_4_ce0;
    end else begin
        validArray_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        if ((ap_predicate_op67_call_state6 == 1'b1)) begin
            validArray_V_d0 = grp_WriteMiss_fu_235_validArray_V_2_d0;
        end else if ((ap_predicate_op65_call_state6 == 1'b1)) begin
            validArray_V_d0 = grp_ReadMiss_fu_201_validArray_V_4_d0;
        end else begin
            validArray_V_d0 = 'bx;
        end
    end else begin
        validArray_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        if ((ap_predicate_op67_call_state6 == 1'b1)) begin
            validArray_V_we0 = grp_WriteMiss_fu_235_validArray_V_2_we0;
        end else if ((ap_predicate_op65_call_state6 == 1'b1)) begin
            validArray_V_we0 = grp_ReadMiss_fu_201_validArray_V_4_we0;
        end else begin
            validArray_V_we0 = 1'b0;
        end
    end else begin
        validArray_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((brmerge1_fu_462_p2 == 1'd1) & (brmerge_fu_450_p2 == 1'd1) & (i_op_read_read_fu_108_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else if (((brmerge1_fu_462_p2 == 1'd1) & (brmerge_fu_450_p2 == 1'd1) & (i_op_read_read_fu_108_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if (((brmerge1_fu_462_p2 == 1'd0) & (brmerge_fu_450_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_ReadHit_fu_269_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((grp_WriteHit_fu_294_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b0 == ap_block_state6_on_subcall_done) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_block_state6_on_subcall_done = (((grp_WriteMiss_fu_235_ap_done == 1'b0) & (ap_predicate_op67_call_state6 == 1'b1)) | ((grp_ReadMiss_fu_201_ap_done == 1'b0) & (ap_predicate_op65_call_state6 == 1'b1)));
end

always @ (*) begin
    ap_condition_758 = ((brmerge1_reg_569 == 1'd1) & (brmerge_reg_565 == 1'd1) & (1'b1 == ap_CS_fsm_state6));
end

always @ (*) begin
    ap_predicate_op65_call_state6 = ((brmerge1_reg_569 == 1'd1) & (brmerge_reg_565 == 1'd1) & (i_op_read_read_fu_108_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op67_call_state6 = ((brmerge1_reg_569 == 1'd1) & (brmerge_reg_565 == 1'd1) & (i_op_read_read_fu_108_p2 == 1'd1));
end

assign ap_return = ap_phi_mux_agg_result_V_2_phi_fu_189_p8;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign brmerge1_fu_462_p2 = (tmp_s_fu_444_p2 | i_op_not_fu_456_p2);

assign brmerge_fu_450_p1 = i_op;

assign brmerge_fu_450_p2 = (tmp_s_fu_444_p2 | brmerge_fu_450_p1);

assign grp_ReadHit_fu_269_ap_start = grp_ReadHit_fu_269_ap_start_reg;

assign grp_ReadMiss_fu_201_ap_start = grp_ReadMiss_fu_201_ap_start_reg;

assign grp_WriteHit_fu_294_ap_start = grp_WriteHit_fu_294_ap_start_reg;

assign grp_WriteMiss_fu_235_ap_start = grp_WriteMiss_fu_235_ap_start_reg;

assign i_op_not_fu_456_p0 = i_op;

assign i_op_not_fu_456_p2 = (i_op_not_fu_456_p0 ^ 1'd1);

assign i_op_read_read_fu_108_p2 = i_op;

integer ap_tvar_int_0;

always @ (i_addr_V) begin
    for (ap_tvar_int_0 = 28 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 31 - 4) begin
            p_Result_2_fu_340_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_2_fu_340_p4[ap_tvar_int_0] = i_addr_V[31 - ap_tvar_int_0];
        end
    end
end

assign p_Result_32_3_fu_432_p5 = {{{{tmp_45_3_fu_426_p2}, {tmp_45_2_fu_407_p2}}, {tmp_45_1_fu_388_p2}}, {tmp_2_fu_369_p2}};

integer ap_tvar_int_1;

always @ (i_addr_V) begin
    for (ap_tvar_int_1 = 4 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 3 - 0) begin
            p_Result_s_fu_321_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            p_Result_s_fu_321_p4[ap_tvar_int_1] = i_addr_V[3 - ap_tvar_int_1];
        end
    end
end

assign tmp_1_fu_364_p2 = ((tagArray_V_0_q0 == p_Result_2_reg_501) ? 1'b1 : 1'b0);

assign tmp_2_fu_369_p2 = (tmp_fu_360_p1 & tmp_1_fu_364_p2);

assign tmp_42_fu_375_p3 = validArray_V_q0[32'd1];

assign tmp_43_fu_394_p3 = validArray_V_q0[32'd2];

assign tmp_44_1_fu_383_p2 = ((tagArray_V_1_q0 == p_Result_2_reg_501) ? 1'b1 : 1'b0);

assign tmp_44_2_fu_402_p2 = ((tagArray_V_2_q0 == p_Result_2_reg_501) ? 1'b1 : 1'b0);

assign tmp_44_3_fu_421_p2 = ((tagArray_V_3_q0 == p_Result_2_reg_501) ? 1'b1 : 1'b0);

assign tmp_44_fu_413_p3 = validArray_V_q0[32'd3];

assign tmp_45_1_fu_388_p2 = (tmp_44_1_fu_383_p2 & tmp_42_fu_375_p3);

assign tmp_45_2_fu_407_p2 = (tmp_44_2_fu_402_p2 & tmp_43_fu_394_p3);

assign tmp_45_3_fu_426_p2 = (tmp_44_fu_413_p3 & tmp_44_3_fu_421_p2);

assign tmp_9_fu_331_p1 = p_Result_s_fu_321_p4;

assign tmp_fu_360_p1 = validArray_V_q0[0:0];

assign tmp_s_fu_444_p2 = ((p_Result_32_3_fu_432_p5 == 4'd0) ? 1'b1 : 1'b0);

endmodule //PLRUCache
